## Data Manipulation module
### Homework assignment 1

Welcome to the first homework assignment of the data manipulation module. In this assignment you will be working with NumPy and Pandas Series. The goal of this assignment is to get you familiar with these libraries and data types.

### Instructions
Read the exercises carefully and implement the requested functionality. Add your code in the cells provided with `YOUR CODE HERE` or `YOUR ANSWER HERE`. You can add cells if you need to. **Make sure to use NumPy methods** to find your answers. In some cases you might be able to read the answer, but we want to see you using the NumPy methods.

### Hand-in
To hand in your assignment, fork this notebook and commit your changes, then make a pull request to the original repository. The deadline for handing in the assignment is **Wednesday 10-05 23:59**.

In [58]:
# imports, no need to edit

import numpy as np
import pandas as pd

np.random.seed(42)

1. Explain the difference between a vector and matrix in NumPy in one sentence.

A Vector is an array with one dimension, a Matrix is an array with two dimensions.

2. Construct a NumPy Array from a list of 10 elements.

In [8]:
array = np.array([1,2,3,4,5,6,7,8,9,10])
print(array)

[ 1  2  3  4  5  6  7  8  9 10]


3. Construct a 10x10 matrix filled with '0's of the integer data type.

In [7]:
array = np.zeros((10,10),dtype=np.int64)
print (array)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


4. Construct a 10x10 matrix filled with '1's, data type float.

In [10]:
array = np.ones((10,10),dtype=np.float64)
print (array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


5. Construct a 10x10 matrix filled with '9's of the integer data type.

In [16]:
array = np.full((10,10),9,dtype=np.int64)
print (array)

[[9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]]


6. Construct a one-dimensional array with values between 5 and 25 that jumps with steps of 3 (`[5, 8, ...]`)

In [17]:
array = np.arange(5,25,3)
print (array)

[ 5  8 11 14 17 20 23]


7. Create an array of size 30 with evenly spaced values between -1 and 1.

In [23]:
array = np.linspace(-1,1,num=30)
print (array)

[-1.         -0.93103448 -0.86206897 -0.79310345 -0.72413793 -0.65517241
 -0.5862069  -0.51724138 -0.44827586 -0.37931034 -0.31034483 -0.24137931
 -0.17241379 -0.10344828 -0.03448276  0.03448276  0.10344828  0.17241379
  0.24137931  0.31034483  0.37931034  0.44827586  0.51724138  0.5862069
  0.65517241  0.72413793  0.79310345  0.86206897  0.93103448  1.        ]


8. Construct a 5x6 matrix with integers from 0 to 30.

In [30]:
array = np.arange(30).reshape(5,6)
print(array)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


9. Create an array of 30 random integers and sort it in ascending order.

In [3]:
from numpy import random
array = np.random.randint(30, size=(30))
print(np.sort(array))


[ 1  1  2  3  5  6  6  7  7 10 10 10 11 14 18 19 20 20 20 20 21 22 23 23
 23 25 27 28 28 29]


10. Construct a 5x10 matrix filled with the value 1 at each location. Print the following details about this matrix:
- number of elements
- shape of the matrix
- the data type (using numpy methods)


In [49]:
array = np.ones((5,10))
print(array.size)
print(array.shape)
print(array.dtype)

50
(5, 10)
float64


11. Construct a 3x4x7 matrix with random integer values between 0 and 10 (a 3D matrix will be created).


In [51]:
array = np.random.randint(0,10, size=(3,4,7))
print(array)

[[[8 5 2 3 3 2 9]
  [2 2 3 6 3 8 0]
  [7 6 1 7 0 8 8]
  [1 6 9 2 6 9 8]]

 [[3 0 1 0 4 4 6]
  [8 8 2 2 2 3 7]
  [5 7 0 7 3 0 7]
  [3 5 7 3 2 8 2]]

 [[8 1 1 1 5 2 8]
  [3 0 3 0 4 3 7]
  [7 6 2 0 0 2 5]
  [6 5 5 5 2 5 7]]]


12. Create an array of 20 random integers and reshape it into a 4x5 matrix.

In [63]:
array=np.random.randint(100,size=20)
# print(array)

print(array.reshape(4,5))

[[13 75 86 14 91]
 [97 65 31 86 62]
 [85 50 24 57 62]
 [61 21 57 57 85]]


13. Construct a one-dimensional array by concetanating 4 separate one-dimensional arrays.

In [62]:
array = np.array([[1], [5], [9],[2]])
print(array)

[[1]
 [5]
 [9]
 [2]]


14. Create a vector of length 3 (3x1) and a matrix of size 3x3. Combine these two arrays on a
    column-by-column basis using numpy methods.


In [14]:
a = np.array([1, 2, 3]).reshape(-1, 1)
b = np.random.randint(0, 10, (3, 3))
# print(a)
# print(b)
print(np.concatenate([a,b], axis=1))

[[1]
 [2]
 [3]]
[[9 6 9]
 [8 6 8]
 [7 1 0]]
[[1 9 6 9]
 [2 8 6 8]
 [3 7 1 0]]


15. What is the difference between "axis=1" and "axis=0" in Numpy functions? 

Axis 1 is the axis that runs horizontally across the columns of the NumPy arrays, axis 0 is the axis that runs downward down the rows in 2D arrays in Numpy

16. Create a random 1D vector with 20 elements. Find the 3rd, 5th and 7th elements of this vector.


In [16]:
array=np.random.randint(100,size=20)
print(array)
print(array[2])
print(array[4])
print(array[6])

[ 8 78 14 89 41 76 50 62 95 51 95  3 93 22 14 42 28 35 12 31]
14
41
50


17. Create a random vector with 10 elements and replace the 4th element of this array with a different number.

In [18]:
array=np.random.randint(100,size=10)
print(array)
array[3] = 99
print(array)

[27 27 43 83 29 61 74 91 88 61]
[27 27 43 99 29 61 74 91 88 61]


18. Look up the concepts of *diagonal matrix* and *trace matrix* online and write a small explanation about what they are.


Diagonal matrix (function) is used to extract a diagonal array from the given array or construct a diagonal array. 
Trace of Matrix is the sum of main diagonal elements of the matrix.

19. Create a 5x5 diagonal matrix with elements of your choosing. What are the indexes of the diagonal?


In [31]:
matrix=np.diag([1,2,3,4,5])
print(matrix)
di = np.diag_indices(5)
print(di)


[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
(array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4]))


20. Create a vector that ranges from 10 to 20. Print the values from the 3rd index to the last index.


In [23]:
array=np.arange(10,20)
print(array)
print(array[2:]) 

[10 11 12 13 14 15 16 17 18 19]
[12 13 14 15 16 17 18 19]


21. Construct a 10x10 matrix with random elements and perform the following indexing tasks on it. Each task should be a single indexing operation.
 - Retrieve column 5 of row 3. Moreover;
 - Retrieve all elements of column 5.
 - Retrieve the 2nd row of all columns.
 - Retrieve row 2 through 7 of all columns.
 - Retrieve values with row index 2 to 5 and column index 3 to 7.
 - Retrieve the values from row index 5 to the end and column index from the top to 4.
 - Replace the value corresponding to the 5th row and the 5th column with your year of birth.

In [51]:
array = np.random.randint(0,100,(10, 10))
print(array)
print(array[2,4])
print(array[:,4])
print(array[1,:])
print(array[1,7:])
print(array[2:5,3:7])
print(array[5:,:4])
array[4,4]=1984
print(array)


[[21 25 27 84 48 70 80 83 48 19]
 [85 91 62 60 48 70  0 95 12 93]
 [86 50 55 82 61 31 29 28 48 44]
 [92 29 15 39 18 17  0 77 46 65]
 [91 93 37 50 62  3  0  7 28 54]
 [ 2 31  9 73 82 33 96 86 54 91]
 [31 49  6 92  7 64 56 66 87 86]
 [58 71 53 66 50 96 91  7 33 34]
 [95 87 77 31 45 15 67 36 53 84]
 [13 94 54 47 81  6 73  6 32 22]]
[[  21   25   27   84   48   70   80   83   48   19]
 [  85   91   62   60   48   70    0   95   12   93]
 [  86   50   55   82   61   31   29   28   48   44]
 [  92   29   15   39   18   17    0   77   46   65]
 [  91   93   37   50 1984    3    0    7   28   54]
 [   2   31    9   73   82   33   96   86   54   91]
 [  31   49    6   92    7   64   56   66   87   86]
 [  58   71   53   66   50   96   91    7   33   34]
 [  95   87   77   31   45   15   67   36   53   84]
 [  13   94   54   47   81    6   73    6   32   22]]


22. Construct a one-dimensional array from 0 to 50 jumping with steps of 5 (`[5, 10, ...]`). Use the numpy methods to perform the following tasks;
- Print all values greater than 20.
- Print all values less than 30.
- How many values are 33 in it?
- Multiply all the elements of the created array by 5.

In [57]:
array = np.arange(0,50,5)
print (array)
index= array>20
print(array[index])
index= array<30
print(array[index])
array=array*5
print (array)

[ 0  5 10 15 20 25 30 35 40 45]
[25 30 35 40 45]
[ 0  5 10 15 20 25]
[  0  25  50  75 100 125 150 175 200 225]


23. Construct an array of 50 random floats between 0 and 1 and take the average. Moreover;
- Get the standard deviation.
- Get the variance.
- Take the median.
- Find the smallest value.
- Find the largest value.

In [64]:
array = np.linspace(0,1,num=50)

print (array.mean())
print(array.std())
print(array.var())
print(np.median(array))
print(array.min())
print(array.max())

0.5
0.2945075446869757
0.086734693877551
0.5
0.0
1.0


24. What are the differences between Pandas Series and NumPy arrays?

the Numpy Array has an implicitly defined integer index used to access the values, the Pandas Series has an explicitly defined index associated with the values

25. Create a 5-element series with different data types, with an index of capital letters.

In [70]:
s1=pd.Series(['8','all you need is..', '25.5', 'False','1000'], index=['A','B','C','D','E'])
print(s['B'])

all you need is..


26. Create a 5-element dictionary with keys as country names and values as capitals and turn it into a series. An example: ` "france" : "paris"`).

In [84]:
dic ={'Gemany':'Berlin','France':'Paris','Nederland':'Amsterdam','Italy':'Rome','Spain':'Madrid'}
s =pd.Series(dic)
print(s)

Gemany          Berlin
France           Paris
Nederland    Amsterdam
Itali             Rome
Spain           Madrid
dtype: object


27. Create a random vector with 10 elements.
- Convert the vector to series and with strings as indeces. For example, a,b,c,d,e,f,g..
- Retrieve the 3rd element of the series using the index name (for example: c).
- Retrieve the 1st element of the series using the index number.
- Access the 2nd and 7th elements of the series at the same time, using the index name. (Example: values corresponding to index b and g)

In [96]:
array= np.random.randint(10, size=10)
s = pd.Series(array, index=['a','b','c','d','e','f','g','h','i','j'])
print(array)
print(s)
print(s['c'])
print(s[0])
print(s[['b','g']])

[8 7 1 0 6 6 7 4 2 7]
a    8
b    7
c    1
d    0
e    6
f    6
g    7
h    4
i    2
j    7
dtype: int32
1
8
b    7
g    7
dtype: int32


28. Create two 5-element series with elements of your choice with default index.
- Combine the series you have created.
- Arrange the index of the resulting concatenated 10-element series from 1 to 10.

In [82]:
s1=pd.Series(['21','22','23','24','25'])
s2=pd.Series(['31','32','33','34','35'])
# s3=pd.concat([s1,s2])
s3=s1.append(s2, ignore_index=True)
# print(s3)
s3.index=s3.index+1
print(s3)


1     21
2     22
3     23
4     24
5     25
6     31
7     32
8     33
9     34
10    35
dtype: object


C:\Users\User\AppData\Local\Temp\ipykernel_11400\46838995.py:4: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  s3=s1.append(s2, ignore_index=True)


**Bonus homework**:


Generate two 20x20 matrices with values between 0 and 1 randomly in a loop and take the difference of these
matrices. Repeat this process until all elements on the diagonal of the difference matrix
is between -0.1 and 0.1. When the desired matrix is found, let the program stop
and print the total number of cycles, how long it took, and the desired matrix
with print.


Tip: Finding the 20 x 20 matrix can take hours. Therefore, to test the accuracy
of your algorithm, you can first try it on small matrices such as 4x4, 5x5. And
you can try the latest 20x20 by increasing the number of matrix. (You can do
the matrix generation with the np.random.random((a,b)) function. It generates
an array of desired sizes between 0-1.)


In [8]:
# YOUR CODE HERE
import numpy as np
np.random.seed(42)
import time

size = 10

# record how long the while loop takes
start = time.time()

while True:
    # generate two random matrices of size 3x3
    a = np.random.random((size, size))
    b = np.random.random((size, size))

    diff = np.abs(a - b)
    # get diagonal of diff
    if np.all(np.diag(diff) <= 0.1):
        print("Found a match!")
        print("matrix 1:")
        print(a)
        print("matrix 2:")
        print(b)
        print("diagonal of diff:")
        print(np.diagonal(diff))
        break

# stop time
end = time.time()
print("Time taken: ", end - start)


[[0.80203982 0.30776679 0.96514057 0.22254882 0.96082357 0.88386248
  0.70451455 0.81831221 0.14548417 0.8959089 ]
 [0.98036683 0.14353201 0.28529909 0.69382485 0.60194746 0.475862
  0.31297111 0.97058358 0.17919567 0.15907398]
 [0.41137242 0.48203334 0.46616916 0.76720021 0.29136543 0.0795811
  0.78117109 0.12738464 0.68651872 0.39496577]
 [0.54496983 0.37466624 0.0617913  0.53042882 0.40448796 0.76969605
  0.20853571 0.51940513 0.91002657 0.00812047]
 [0.51407471 0.65924698 0.27077373 0.26043534 0.87028382 0.48404125
  0.11449501 0.35794764 0.08981719 0.08823397]
 [0.38782498 0.68402206 0.11227034 0.50878429 0.48766131 0.12199372
  0.95849971 0.98251215 0.55170378 0.59825786]
 [0.41522148 0.70202938 0.21248676 0.22896877 0.15433878 0.25010281
  0.46566852 0.06914628 0.39681494 0.55999141]
 [0.41197287 0.69454831 0.32287117 0.96678505 0.83378521 0.7331555
  0.70858667 0.12600876 0.34546425 0.00619238]
 [0.52984152 0.37588775 0.56028108 0.05727417 0.24793042 0.68294765
  0.52578849 0.6