## Data Manipulation module
### Homework assignment 1

Welcome to the first homework assignment of the data manipulation module. In this assignment you will be working with NumPy and Pandas Series. The goal of this assignment is to get you familiar with these libraries and data types.

### Instructions
Read the exercises carefully and implement the requested functionality. Add your code in the cells provided with `YOUR CODE HERE` or `YOUR ANSWER HERE`. You can add cells if you need to. **Make sure to use NumPy methods** to find your answers. In some cases you might be able to read the answer, but we want to see you using the NumPy methods.

### Hand-in
To hand in your assignment, fork this notebook and commit your changes, then make a pull request to the original repository. The deadline for handing in the assignment is **Wednesday 10-05 23:59**.

In [1]:
# imports, no need to edit

import numpy as np
import pandas as pd

np.random.seed(42)

1. Explain the difference between a vector and matrix in NumPy in one sentence.

YOUR ANSWER HERE

2. Construct a NumPy Array from a list of 10 elements.

In [3]:
# YOUR CODE HERE
my_list = [1,2,3,4,5,6,7,8,9,10]
my_array = np.array(my_list)
my_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

3. Construct a 10x10 matrix filled with '0's of the integer data type.

In [4]:
# YOUR CODE HERE
my_matrix = np.zeros((10,10), dtype=int)
my_matrix

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

4. Construct a 10x10 matrix filled with '1's, data type float.

In [5]:
# YOUR CODE HERE
my_matrix = np.ones((10,10), dtype=float)
my_matrix

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

5. Construct a 10x10 matrix filled with '9's of the integer data type.

In [10]:
# YOUR CODE HERE
my_matrix = np.full((10,10),9, dtype=int)
my_matrix

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

6. Construct a one-dimensional array with values between 5 and 25 that jumps with steps of 3 (`[5, 8, ...]`)

In [11]:
# YOUR CODE HERE
my_dimension = np.arange(5,25,3)
my_dimension

array([ 5,  8, 11, 14, 17, 20, 23])

7. Create an array of size 30 with evenly spaced values between -1 and 1.

In [12]:
# YOUR CODE HERE
my_array = np.linspace(-1,1,30)
my_array

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

8. Construct a 5x6 matrix with integers from 0 to 30.

In [13]:
# YOUR CODE HERE
my_matrix = np.random.randint(0, 30, size=(5,6))
my_matrix

array([[ 6, 19, 28, 14, 10,  7],
       [28, 20,  6, 25, 18, 22],
       [10, 10, 23, 20,  3,  7],
       [23,  2, 21, 20,  1, 23],
       [11, 29,  5,  1, 27, 20]])

9. Create an array of 30 random integers and sort it in ascending order.

In [21]:
# YOUR CODE HERE
my_array = np.random.randint(0, 50, 30)
my_array=np.sort(my_array)
my_array

array([ 0,  0,  4,  6,  7,  7,  8, 10, 14, 16, 17, 23, 23, 23, 24, 24, 25,
       27, 28, 32, 34, 34, 38, 40, 40, 41, 43, 44, 44, 46])

10. Construct a 5x10 matrix filled with the value 1 at each location. Print the following details about this matrix:
- number of elements
- shape of the matrix
- the data type (using numpy methods)


In [28]:
# YOUR CODE HERE
x = np.ones((5,10))
print("numberof elemrnts", x.size)
print("shape of the matrix", x.shape)
print("the data type of matrix", x.dtype)

numberof elemrnts 50
shape of the matrix (5, 10)
the data type of matrix float64


11. Construct a 3x4x7 matrix with random integer values between 0 and 10 (a 3D matrix will be created).


In [29]:
# YOUR CODE HERE
my_matrix_3d = np.random.randint(0,10,size=(3,4,7), dtype=int)
my_matrix_3d

array([[[6, 8, 7, 1, 0, 6, 6],
        [7, 4, 2, 7, 5, 2, 0],
        [2, 4, 2, 0, 4, 9, 6],
        [6, 8, 9, 9, 2, 6, 0]],

       [[3, 3, 4, 6, 6, 3, 6],
        [2, 5, 1, 9, 8, 4, 5],
        [3, 9, 6, 8, 6, 0, 0],
        [8, 8, 3, 8, 2, 6, 5]],

       [[7, 8, 4, 0, 2, 9, 7],
        [5, 7, 8, 3, 0, 0, 9],
        [3, 6, 1, 2, 0, 4, 0],
        [7, 0, 0, 1, 1, 5, 6]]])

12. Create an array of 20 random integers and reshape it into a 4x5 matrix.

In [44]:
# YOUR CODE HERE
my_array = np.random.randint(0, 50, size=20)
my_array.reshape((4,5))

array([[ 6, 40, 32, 39, 38],
       [17, 39,  0, 10, 27],
       [24, 49, 22, 30, 29],
       [41, 34,  6, 15, 25]])

13. Construct a one-dimensional array by concetanating 4 separate one-dimensional arrays.

In [47]:
# YOUR CODE HERE
my_array_1 = np.array([1, 2, 3])
my_array_2 = np.array([4,5,6])
my_array_3 = np.array([7,8])
my_array_4 = np.array([9])

my_array = np.concatenate((my_array_1,my_array_2,my_array_3,my_array_4))
my_array


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

14. Create a vector of length 3 (3x1) and a matrix of size 3x3. Combine these two arrays on a
    column-by-column basis using numpy methods.


In [49]:
a = np.array([1, 2, 3]).reshape(-1, 1)
b = np.random.randint(0, 10, (3, 3))


In [53]:
comine = np.concatenate((a,b), axis=1)
comine

array([[1, 8, 3, 0],
       [2, 1, 0, 4],
       [3, 4, 6, 8]])

15. What is the difference between "axis=1" and "axis=0" in Numpy functions? 

YOUR ANSWER HERE

"axis = 0" is performed along the rows of an array

"axis = 1" is performed along the columns of an array

16. Create a random 1D vector with 20 elements. Find the 3rd, 5th and 7th elements of this vector.


In [56]:
# YOUR CODE HERE
v= np.random.randint(1, 50, 20)
print("This is 1D vector with 20 elements:\n",v)
finde_element = v[[2,4,6]]
print("This value is 3rd, 5th, and 7th elements:\n",finde_element)

This is 1D vector with 20 elements:
 [ 3 17 33 48 12 22 22 46 30 38 38 45  8 27 27 34 21 30 33 28]
This value is 3rd, 5th, and 7th elements:
 [33 12 22]


17. Create a random vector with 10 elements and replace the 4th element of this array with a different number.

In [63]:
# YOUR CODE HERE
v = np.random.randint(1, 50 , 10)
print("This the 10 random numbers:\n", v)
replace_element = v[[3]] = [10]


print("This new random number:\n",v)


This the 10 random numbers:
 [13  7 36 45 20  1  8 46 16 14]
This new random number:
 [13  7 36 10 20  1  8 46 16 14]


18. Look up the concepts of *diagonal matrix* and *trace matrix* online and write a small explanation about what they are.


YOUR ANSWER HERE

19. Create a 5x5 diagonal matrix with elements of your choosing. What are the indexes of the diagonal?


In [64]:
# YOUR CODE HERE
my_diagonal = np.diag([1,2,3,4,5])
my_diagonal

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

20. Create a vector that ranges from 10 to 20. Print the values from the 3rd index to the last index.


In [66]:
# YOUR CODE HERE
my_array = np.arange(10, 20)
my_array[3:]

array([13, 14, 15, 16, 17, 18, 19])

21. Construct a 10x10 matrix with random elements and perform the following indexing tasks on it. Each task should be a single indexing operation.
 - Retrieve column 5 of row 3. Moreover;
 - Retrieve all elements of column 5.
 - Retrieve the 2nd row of all columns.
 - Retrieve row 2 through 7 of all columns.
 - Retrieve values with row index 2 to 5 and column index 3 to 7.
 - Retrieve the values from row index 5 to the end and column index from the top to 4.
 - Replace the value corresponding to the 5th row and the 5th column with your year of birth.

In [85]:
# YOUR CODE HERE
my_matrix = np.random.randint(0,50, size=(10,10))
print(my_matrix)
print("column 5 of row 3:", my_matrix[2,4])
print("All column 5 :", my_matrix[:4])
print("Retrieve the 2nd row of all columns:",my_matrix[1, :])
print(my_matrix[1:7, :])
print(my_matrix[1:5, 2:7])
print(my_matrix[4:, :4])
my_matrix[4, 4] = 1998



[[43 19 23 49 48 31 40 35 33 35]
 [ 1 14 33 35  5 38 41 11  2 44]
 [17 39 20 14 32 34 25  7 35 47]
 [29 22 41 43 13 13  1 36  4 37]
 [44 40 46 13 38 24 19  1 38  5]
 [16 24 27  1 34 36  4  0 39 11]
 [35 44 22 46 30 10  9  2 13 15]
 [ 9 28  9 11 29 40  0  4 19  7]
 [42 11  0 19 27 42 36 46 36 11]
 [36 48 48 43 27 46 14  5 43 19]]
column 5 of row 3: 32
All column 5 : [[43 19 23 49 48 31 40 35 33 35]
 [ 1 14 33 35  5 38 41 11  2 44]
 [17 39 20 14 32 34 25  7 35 47]
 [29 22 41 43 13 13  1 36  4 37]]
Retrieve the 2nd row of all columns: [ 1 14 33 35  5 38 41 11  2 44]
[[ 1 14 33 35  5 38 41 11  2 44]
 [17 39 20 14 32 34 25  7 35 47]
 [29 22 41 43 13 13  1 36  4 37]
 [44 40 46 13 38 24 19  1 38  5]
 [16 24 27  1 34 36  4  0 39 11]
 [35 44 22 46 30 10  9  2 13 15]]
[[33 35  5 38 41]
 [20 14 32 34 25]
 [41 43 13 13  1]
 [46 13 38 24 19]]
[[44 40 46 13]
 [16 24 27  1]
 [35 44 22 46]
 [ 9 28  9 11]
 [42 11  0 19]
 [36 48 48 43]]


22. Construct a one-dimensional array from 0 to 50 jumping with steps of 5 (`[5, 10, ...]`). Use the numpy methods to perform the following tasks;
- Print all values greater than 20.
- Print all values less than 30.
- How many values are 33 in it?
- Multiply all the elements of the created array by 5.

In [92]:
# YOUR CODE HERE
my_array = np.arange(0, 50, 5)
print(my_array[my_array > 20])
print(my_array[my_array < 30])
print(np.count_nonzero(my_array == 33))
print(my_array * 5)


[25 30 35 40 45]
[ 0  5 10 15 20 25]
0
[  0  25  50  75 100 125 150 175 200 225]


23. Construct an array of 50 random floats between 0 and 1 and take the average. Moreover;
- Get the standard deviation.
- Get the variance.
- Take the median.
- Find the smallest value.
- Find the largest value.

In [94]:
# YOUR CODE HERE
my_array = np.random.rand(50)

print(np.std(my_array))
print(np.average(my_array))
print(np.var(my_array))
print(np.median(my_array))
print(np.min(my_array))
print(np.max(my_array))


0.2550147963560986
0.520293237254069
0.06503254636054244
0.5263421659315483
0.0057586604981215705
0.9994137257706666


24. What are the differences between Pandas Series and NumPy arrays?

YOUR ANSWER HERE

25. Create a 5-element series with different data types, with an index of capital letters.

In [95]:
# YOUR CODE HERE
my_se = pd.Series(['Girmay', 25, 1.0, True, None], index=['A','B','C','D','E'])
print(my_se)

A    Girmay
B         2
C       1.0
D      True
E      None
dtype: object


26. Create a 5-element dictionary with keys as country names and values as capitals and turn it into a series. An example: ` "france" : "paris"`).

In [96]:
# YOUR CODE HERE
x = {'frances':'paris','USA':'washinfton D.C.', 'Italy':'Rome', 'Netherlands':'Amsdrdem','ethiopia':'Addis Ababa'}
print(pd.Series(x))

frances                  paris
USA            washinfton D.C.
Italy                     Rome
Netherlands           Amsdrdem
ethiopia           Addis Ababa
dtype: object


27. Create a random vector with 10 elements.
- Convert the vector to series and with strings as indeces. For example, a,b,c,d,e,f,g..
- Retrieve the 3rd element of the series using the index name (for example: c).
- Retrieve the 1st element of the series using the index number.
- Access the 2nd and 7th elements of the series at the same time, using the index name. (Example: values corresponding to index b and g)

In [112]:
# YOUR CODE HERE
x = np.random.randint(1,20,10)
print("Element:",x)
my_series = pd.Series(x, index = ['A', 'B', 'C','D','E','F','G','H','I','J'])
print(my_series)
print("3rd element of the series using the index name:",my_series['C'])
print("1st element of the series using the index number:",my_series[0])
print("2nd and 7th elements of the series at the same time, using the index name:",my_series[['C','H']])

Element: [18  3 12  3  6  2 12  2  6 17]
A    18
B     3
C    12
D     3
E     6
F     2
G    12
H     2
I     6
J    17
dtype: int64
3rd element of the series using the index name: 12
1st element of the series using the index number: 18
2nd and 7th elements of the series at the same time, using the index name: C    12
H     2
dtype: int64


28. Create two 5-element series with elements of your choice with default index.
- Combine the series you have created.
- Arrange the index of the resulting concatenated 10-element series from 1 to 10.

In [118]:
# YOUR CODE HERE
my_series1 = pd.Series([1,2,3,4,5])
my_series2= pd.Series([6,7,8,9,10])
com = pd.concat([my_series1, my_series2])
print(com)
new = pd.Series(com.values, index=range(1, 11))
print(new)



0     1
1     2
2     3
3     4
4     5
0     6
1     7
2     8
3     9
4    10
dtype: int64
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64


**Bonus homework**:


Generate two 20x20 matrices with values between 0 and 1 randomly in a loop and take the difference of these
matrices. Repeat this process until all elements on the diagonal of the difference matrix
is between -0.1 and 0.1. When the desired matrix is found, let the program stop
and print the total number of cycles, how long it took, and the desired matrix
with print.


Tip: Finding the 20 x 20 matrix can take hours. Therefore, to test the accuracy
of your algorithm, you can first try it on small matrices such as 4x4, 5x5. And
you can try the latest 20x20 by increasing the number of matrix. (You can do
the matrix generation with the np.random.random((a,b)) function. It generates
an array of desired sizes between 0-1.)


In [8]:
# YOUR CODE HERE
import numpy as np
np.random.seed(42)
import time

size = 10

# record how long the while loop takes
start = time.time()

while True:
    # generate two random matrices of size 3x3
    a = np.random.random((size, size))
    b = np.random.random((size, size))

    diff = np.abs(a - b)
    # get diagonal of diff
    if np.all(np.diag(diff) <= 0.1):
        print("Found a match!")
        print("matrix 1:")
        print(a)
        print("matrix 2:")
        print(b)
        print("diagonal of diff:")
        print(np.diagonal(diff))
        break

# stop time
end = time.time()
print("Time taken: ", end - start)


[[0.80203982 0.30776679 0.96514057 0.22254882 0.96082357 0.88386248
  0.70451455 0.81831221 0.14548417 0.8959089 ]
 [0.98036683 0.14353201 0.28529909 0.69382485 0.60194746 0.475862
  0.31297111 0.97058358 0.17919567 0.15907398]
 [0.41137242 0.48203334 0.46616916 0.76720021 0.29136543 0.0795811
  0.78117109 0.12738464 0.68651872 0.39496577]
 [0.54496983 0.37466624 0.0617913  0.53042882 0.40448796 0.76969605
  0.20853571 0.51940513 0.91002657 0.00812047]
 [0.51407471 0.65924698 0.27077373 0.26043534 0.87028382 0.48404125
  0.11449501 0.35794764 0.08981719 0.08823397]
 [0.38782498 0.68402206 0.11227034 0.50878429 0.48766131 0.12199372
  0.95849971 0.98251215 0.55170378 0.59825786]
 [0.41522148 0.70202938 0.21248676 0.22896877 0.15433878 0.25010281
  0.46566852 0.06914628 0.39681494 0.55999141]
 [0.41197287 0.69454831 0.32287117 0.96678505 0.83378521 0.7331555
  0.70858667 0.12600876 0.34546425 0.00619238]
 [0.52984152 0.37588775 0.56028108 0.05727417 0.24793042 0.68294765
  0.52578849 0.6