## Data Manipulation module
### Homework assignment 1

Welcome to the first homework assignment of the data manipulation module. In this assignment you will be working with NumPy and Pandas Series. The goal of this assignment is to get you familiar with these libraries and data types.

### Instructions
Read the exercises carefully and implement the requested functionality. Add your code in the cells provided with `YOUR CODE HERE` or `YOUR ANSWER HERE`. You can add cells if you need to. **Make sure to use NumPy methods** to find your answers. In some cases you might be able to read the answer, but we want to see you using the NumPy methods.

### Hand-in
To hand in your assignment, fork this notebook and commit your changes, then make a pull request to the original repository. The deadline for handing in the assignment is **Wednesday 10-05 23:59**.

In [4]:
# imports, no need to edit

import numpy as np
import pandas as pd

np.random.seed(42)

1. Explain the difference between a vector and matrix in NumPy in one sentence.

Vector always is one-dimentional, and matrix has more then 2 dimentions.

2. Construct a NumPy Array from a list of 10 elements.

In [39]:
np.array([5, 6, 7, 3, 4, 8, 7, 6, 1, 67])

array([ 5,  6,  7,  3,  4,  8,  7,  6,  1, 67])

3. Construct a 10x10 matrix filled with '0's of the integer data type.

In [8]:
np.zeros((10,10)).astype('int32')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

4. Construct a 10x10 matrix filled with '1's, data type float.

In [9]:
np.ones((10,10), 'float')

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

5. Construct a 10x10 matrix filled with '9's of the integer data type.

In [13]:
np.full((10,10), 9, 'int')

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

6. Construct a one-dimensional array with values between 5 and 25 that jumps with steps of 3 (`[5, 8, ...]`)

In [22]:
np.arange(5,25,3)

array([ 5,  8, 11, 14, 17, 20, 23])

7. Create an array of size 30 with evenly spaced values between -1 and 1.

In [23]:
np.linspace(-1, 1, num=30)

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

8. Construct a 5x6 matrix with integers from 0 to 30.

In [32]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

9. Create an array of 30 random integers and sort it in ascending order.

In [9]:
matrix = np.sort(np.random.randint(30, size=(30)))
matrix

array([ 1,  3,  3,  7,  7,  9,  9, 11, 12, 13, 13, 14, 14, 15, 15, 17, 17,
       20, 20, 21, 21, 22, 23, 24, 25, 25, 27, 28, 29, 29])

10. Construct a 5x10 matrix filled with the value 1 at each location. Print the following details about this matrix:
- number of elements
- shape of the matrix
- the data type (using numpy methods)


In [17]:
matrix = np.ones((5,10))
print("Size is: ", matrix.size)
print("Shape is: ", matrix.shape)
print("Data type is: ", matrix.dtype)

Size is:  50
Shape is:  (5, 10)
Data type is:  float64


11. Construct a 3x4x7 matrix with random integer values between 0 and 10 (a 3D matrix will be created).


In [19]:
matrix = np.random.randint(0,10, size=(3,4,7))
matrix

array([[[5, 7, 8, 3, 0, 0, 9],
        [3, 6, 1, 2, 0, 4, 0],
        [7, 0, 0, 1, 1, 5, 6],
        [4, 0, 0, 2, 1, 4, 9]],

       [[5, 6, 3, 6, 7, 0, 5],
        [7, 4, 3, 1, 5, 5, 0],
        [8, 5, 2, 3, 3, 2, 9],
        [2, 2, 3, 6, 3, 8, 0]],

       [[7, 6, 1, 7, 0, 8, 8],
        [1, 6, 9, 2, 6, 9, 8],
        [3, 0, 1, 0, 4, 4, 6],
        [8, 8, 2, 2, 2, 3, 7]]])

12. Create an array of 20 random integers and reshape it into a 4x5 matrix.

In [26]:
np.random.randint(100, size=(20)).reshape(4,5)

array([[32, 67, 32, 13, 20],
       [47, 19,  7,  6, 66],
       [16, 32, 47, 75, 58],
       [85, 21, 29, 37, 50]])

13. Construct a one-dimensional array by concetanating 4 separate one-dimensional arrays.

In [36]:
arr1 = np.random.randint(100, size=(10))
arr2 = np.random.randint(100, size=(10))
arr3 = np.random.randint(100, size=(10))
arr4 = np.random.randint(100, size=(10))
np.vstack((arr1, arr2, arr3, arr4))

array([[81, 95, 23, 22, 61, 95, 36, 11, 54, 12],
       [22, 88, 98, 29, 16, 61, 83, 88, 85, 12],
       [58, 18, 48, 99, 11, 60, 18, 75,  8, 70],
       [27, 77, 94, 51, 82, 15, 68, 98, 11, 24]])

14. Create a vector of length 3 (3x1) and a matrix of size 3x3. Combine these two arrays on a
    column-by-column basis using numpy methods.


In [41]:
a = np.array([1, 2, 3]).reshape(-1, 1)
b = np.random.randint(0, 10, (3, 3))
np.hstack((a, b))

array([[1, 9, 6, 9],
       [2, 4, 2, 6],
       [3, 1, 8, 9]])

15. What is the difference between "axis=1" and "axis=0" in Numpy functions? 

axis = 0 - rows
axis = 1 - columns

16. Create a random 1D vector with 20 elements. Find the 3rd, 5th and 7th elements of this vector.


In [48]:
arr = np.random.randint(100, size=20)
arr[[2,4,6]]

array([91, 60,  0])

17. Create a random vector with 10 elements and replace the 4th element of this array with a different number.

In [50]:
arr = np.random.randint(100, size=10)
print('Vector before: ', arr)
arr[3] = 1000
print('Vector after: ', arr)

Vector before:  [18 19 56 17 46 48 13 14 30  0]
Vector after:  [  18   19   56 1000   46   48   13   14   30    0]


18. Look up the concepts of *diagonal matrix* and *trace matrix* online and write a small explanation about what they are.


Diagonal matrix is a matrix in which the entries outside the main diagonal are all zero.
Trace matrix is the sum of elements on the main diadonal af square matrix. 

19. Create a 5x5 diagonal matrix with elements of your choosing. What are the indexes of the diagonal?


In [62]:
matrix = np.arange(3, 28).reshape(5 ,5)
diag = np.diag(matrix)
np.diag(diag)
# indexes of main diagoanl are: [0,0], [1,1], [2,2], [3,3] ...[n,n]

array([[ 3,  0,  0,  0,  0],
       [ 0,  9,  0,  0,  0],
       [ 0,  0, 15,  0,  0],
       [ 0,  0,  0, 21,  0],
       [ 0,  0,  0,  0, 27]])

20. Create a vector that ranges from 10 to 20. Print the values from the 3rd index to the last index.


In [63]:
vector = np.arange(10, 20)
vector[2:]

array([12, 13, 14, 15, 16, 17, 18, 19])

21. Construct a 10x10 matrix with random elements and perform the following indexing tasks on it. Each task should be a single indexing operation.
 - Retrieve column 5 of row 3. Moreover;
 - Retrieve all elements of column 5.
 - Retrieve the 2nd row of all columns.
 - Retrieve row 2 through 7 of all columns.
 - Retrieve values with row index 2 to 5 and column index 3 to 7.
 - Retrieve the values from row index 5 to the end and column index from the top to 4.
 - Replace the value corresponding to the 5th row and the 5th column with your year of birth.

In [70]:
m = np.random.randint(100, size=(10,10))
m

array([[83, 91, 74,  3, 78,  5, 93, 50, 61, 56],
       [65, 78, 74,  7, 25, 50, 44, 43,  4, 69],
       [25, 67, 18, 83, 96, 19, 11, 46,  0, 89],
       [13, 63, 37, 36, 10, 99, 76,  2, 32,  5],
       [49,  9,  4, 22,  9, 43,  1, 12, 39,  1],
       [83, 64, 62, 72, 16,  8, 74, 14, 23, 37],
       [34, 93, 94, 48, 68, 61, 59, 49, 77, 74],
       [ 8, 33, 75, 98, 34,  0, 39, 63, 21, 59],
       [63, 92, 71, 10, 13, 59, 29, 34, 84, 36],
       [ 4, 82, 77, 25, 61,  3, 88, 41, 88, 17]])

In [71]:
# Retrieve column 5 of row 3
m[2,4]

96

In [72]:
# Retrieve all elements of column 5.
m[:, 4]

array([78, 25, 96, 10,  9, 16, 68, 34, 13, 61])

In [73]:
# Retrieve the 2nd row of all columns.
m[1, :]

array([65, 78, 74,  7, 25, 50, 44, 43,  4, 69])

In [75]:
# Retrieve row 2 through 7 of all columns.
m[1:7, :]


array([[65, 78, 74,  7, 25, 50, 44, 43,  4, 69],
       [25, 67, 18, 83, 96, 19, 11, 46,  0, 89],
       [13, 63, 37, 36, 10, 99, 76,  2, 32,  5],
       [49,  9,  4, 22,  9, 43,  1, 12, 39,  1],
       [83, 64, 62, 72, 16,  8, 74, 14, 23, 37],
       [34, 93, 94, 48, 68, 61, 59, 49, 77, 74]])

In [76]:
# Retrieve values with row index 2 to 5 and column index 3 to 7.
m[2:5, 3:7]

array([[83, 96, 19, 11],
       [36, 10, 99, 76],
       [22,  9, 43,  1]])

In [77]:
# Retrieve the values from row index 5 to the end and column index from the top to 4.
m[5:, :4]

array([[83, 64, 62, 72],
       [34, 93, 94, 48],
       [ 8, 33, 75, 98],
       [63, 92, 71, 10],
       [ 4, 82, 77, 25]])

In [82]:
# Replace the value corresponding to the 5th row and the 5th column with your year of birth.
matrix = np.copy(m)
matrix[4, 4] = 1990
matrix

array([[  83,   91,   74,    3,   78,    5,   93,   50,   61,   56],
       [  65,   78,   74,    7,   25,   50,   44,   43,    4,   69],
       [  25,   67,   18,   83,   96,   19,   11,   46,    0,   89],
       [  13,   63,   37,   36,   10,   99,   76,    2,   32,    5],
       [  49,    9,    4,   22, 1990,   43,    1,   12,   39,    1],
       [  83,   64,   62,   72,   16,    8,   74,   14,   23,   37],
       [  34,   93,   94,   48,   68,   61,   59,   49,   77,   74],
       [   8,   33,   75,   98,   34,    0,   39,   63,   21,   59],
       [  63,   92,   71,   10,   13,   59,   29,   34,   84,   36],
       [   4,   82,   77,   25,   61,    3,   88,   41,   88,   17]])

22. Construct a one-dimensional array from 0 to 50 jumping with steps of 5 (`[5, 10, ...]`). Use the numpy methods to perform the following tasks;
- Print all values greater than 20.
- Print all values less than 30.
- How many values are 33 in it?
- Multiply all the elements of the created array by 5.

In [83]:
arr = np.arange(5, 51, 5)


array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [84]:
#Print all values greater than 20.
arr[arr > 20]

array([25, 30, 35, 40, 45, 50])

In [85]:
# Print all values less than 30.
arr[arr < 30]

array([ 5, 10, 15, 20, 25])

In [88]:
# How many values are 33 in it?
np.count_nonzero(arr == 33)

0

In [89]:
# Multiply all the elements of the created array by 5.
arr * 5

array([ 25,  50,  75, 100, 125, 150, 175, 200, 225, 250])

23. Construct an array of 50 random floats between 0 and 1 and take the average. Moreover;
- Get the standard deviation.
- Get the variance.
- Take the median.
- Find the smallest value.
- Find the largest value.

In [90]:
arr = np.random.rand(50)
arr

array([0.81659944, 0.43913491, 0.37694443, 0.46267979, 0.30137787,
       0.74760938, 0.50272039, 0.2322127 , 0.89957457, 0.38389122,
       0.54355286, 0.90647211, 0.624238  , 0.11689804, 0.93983212,
       0.62770805, 0.33490561, 0.13927207, 0.79402519, 0.62007276,
       0.53346109, 0.89389258, 0.78859721, 0.15167488, 0.31172207,
       0.24848914, 0.74394629, 0.03353243, 0.56988968, 0.76245869,
       0.87676564, 0.34208175, 0.8212573 , 0.11063174, 0.84645229,
       0.12748866, 0.39728729, 0.79729537, 0.14991743, 0.2292514 ,
       0.72225257, 0.72003654, 0.64114763, 0.69394844, 0.54272444,
       0.25179906, 0.34569599, 0.18159772, 0.90845056, 0.58339179])

In [91]:
#Get the standard deviation.
np.std(arr)

0.2661237833967229

In [94]:
# Get the variance.
np.mean(arr)

0.5227371839565556

In [95]:
# Take the median.
np.median(arr)

0.5431386522307924

In [92]:
# Find the smallest value.
np.min(arr)

0.03353243473577938

In [93]:
# Find the largest value.
np.max(arr)

0.9398321236134751

24. What are the differences between Pandas Series and NumPy arrays?

1. Pandas Series is a one-dimensional labeled array capable of holding any data type, while NumPy arrays are strictly multidimensional arrays of a single data type.

2. NumPy arrays are faster and use less memory than Pandas Series, but Pandas Series offer more flexibility and additional functionalities.

3. Pandas Series can contain heterogeneous data types, while NumPy arrays only contain homogeneous data.

4. Pandas Series have an explicit index, while NumPy arrays have an implicit index.

5. Pandas Series are built on top of NumPy arrays and provide additional functionalities such as automatic alignment, easy data manipulation, and handling of missing data.

25. Create a 5-element series with different data types, with an index of capital letters.

In [97]:
a = ['wer', 34, 34.56, 0, 3]
indexes = 'A B C D E'.split()
pd.Series(a, indexes)

A      wer
B       34
C    34.56
D        0
E        3
dtype: object

26. Create a 5-element dictionary with keys as country names and values as capitals and turn it into a series. An example: ` "france" : "paris"`).

In [99]:
countries = {
    "ukraine": "kiyv",
    "russia": "moscow",
    'netherlands': 'amsterdam',
    'germany': 'berlin',
    'france': 'paris'
}

pd.Series(countries)

ukraine             kiyv
russia            moscow
netherlands    amsterdam
germany           berlin
france             paris
dtype: object

27. Create a random vector with 10 elements.
- Convert the vector to series and with strings as indeces. For example, a,b,c,d,e,f,g..
- Retrieve the 3rd element of the series using the index name (for example: c).
- Retrieve the 1st element of the series using the index number.
- Access the 2nd and 7th elements of the series at the same time, using the index name. (Example: values corresponding to index b and g)

In [100]:
vector = np.arange(10)
vector

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
# Convert the vector to series and with strings as indeces. For example, a,b,c,d,e,f,g..
series = pd.Series(vector, [i for i in 'abcdefgjik'])
series

a    0
b    1
c    2
d    3
e    4
f    5
g    6
j    7
i    8
k    9
dtype: int64

In [104]:
# Retrieve the 3rd element of the series using the index name (for example: c).
series['c']

2

In [105]:
# Retrieve the 1st element of the series using the index number.
series['a']

0

In [107]:
# Access the 2nd and 7th elements of the series at the same time, using the index name. (Example: values corresponding to index b and g)
series[['b', 'g']]

b    1
g    6
dtype: int64

28. Create two 5-element series with elements of your choice with default index.
- Combine the series you have created.
- Arrange the index of the resulting concatenated 10-element series from 1 to 10.

In [118]:
ser1 = pd.Series([i for i in 'ABCDE'])
ser2 = pd.Series([i for i in 'abcde'])
print( 'First Series: ')
print(ser1)
print()
print( 'Second Series: ')
print(ser2)

First Series: 
0    A
1    B
2    C
3    D
4    E
dtype: object

Second Series: 
0    a
1    b
2    c
3    d
4    e
dtype: object


In [128]:
# Combine the series you have created.
concat = pd.concat([ser1, ser2])
concat

0    A
1    B
2    C
3    D
4    E
0    a
1    b
2    c
3    d
4    e
dtype: object

In [127]:
# Arrange the index of the resulting concatenated 10-element series from 1 to 10.
# ser1.append(ser2, ignore_index = True)
# In pd 2.0, append has been removed

new = concat.reset_index()
new


index  0
0      0  A
1      1  B
2      2  C
3      3  D
4      4  E
5      0  a
6      1  b
7      2  c
8      3  d
9      4  e

**Bonus homework**:


Generate two 20x20 matrices with values between 0 and 1 randomly in a loop and take the difference of these
matrices. Repeat this process until all elements on the diagonal of the difference matrix
is between -0.1 and 0.1. When the desired matrix is found, let the program stop
and print the total number of cycles, how long it took, and the desired matrix
with print.


Tip: Finding the 20 x 20 matrix can take hours. Therefore, to test the accuracy
of your algorithm, you can first try it on small matrices such as 4x4, 5x5. And
you can try the latest 20x20 by increasing the number of matrix. (You can do
the matrix generation with the np.random.random((a,b)) function. It generates
an array of desired sizes between 0-1.)


In [8]:
# YOUR CODE HERE
import numpy as np
np.random.seed(42)
import time

size = 10

# record how long the while loop takes
start = time.time()

while True:
    # generate two random matrices of size 3x3
    a = np.random.random((size, size))
    b = np.random.random((size, size))

    diff = np.abs(a - b)
    # get diagonal of diff
    if np.all(np.diag(diff) <= 0.1):
        print("Found a match!")
        print("matrix 1:")
        print(a)
        print("matrix 2:")
        print(b)
        print("diagonal of diff:")
        print(np.diagonal(diff))
        break

# stop time
end = time.time()
print("Time taken: ", end - start)


[[0.80203982 0.30776679 0.96514057 0.22254882 0.96082357 0.88386248
  0.70451455 0.81831221 0.14548417 0.8959089 ]
 [0.98036683 0.14353201 0.28529909 0.69382485 0.60194746 0.475862
  0.31297111 0.97058358 0.17919567 0.15907398]
 [0.41137242 0.48203334 0.46616916 0.76720021 0.29136543 0.0795811
  0.78117109 0.12738464 0.68651872 0.39496577]
 [0.54496983 0.37466624 0.0617913  0.53042882 0.40448796 0.76969605
  0.20853571 0.51940513 0.91002657 0.00812047]
 [0.51407471 0.65924698 0.27077373 0.26043534 0.87028382 0.48404125
  0.11449501 0.35794764 0.08981719 0.08823397]
 [0.38782498 0.68402206 0.11227034 0.50878429 0.48766131 0.12199372
  0.95849971 0.98251215 0.55170378 0.59825786]
 [0.41522148 0.70202938 0.21248676 0.22896877 0.15433878 0.25010281
  0.46566852 0.06914628 0.39681494 0.55999141]
 [0.41197287 0.69454831 0.32287117 0.96678505 0.83378521 0.7331555
  0.70858667 0.12600876 0.34546425 0.00619238]
 [0.52984152 0.37588775 0.56028108 0.05727417 0.24793042 0.68294765
  0.52578849 0.6