## Data Manipulation module
### Homework assignment 1

Welcome to the first homework assignment of the data manipulation module. In this assignment you will be working with NumPy and Pandas Series. The goal of this assignment is to get you familiar with these libraries and data types.

### Instructions
Read the exercises carefully and implement the requested functionality. Add your code in the cells provided with `YOUR CODE HERE` or `YOUR ANSWER HERE`. You can add cells if you need to. **Make sure to use NumPy methods** to find your answers. In some cases you might be able to read the answer, but we want to see you using the NumPy methods.

### Hand-in
To hand in your assignment, fork this notebook and commit your changes, then make a pull request to the original repository. The deadline for handing in the assignment is **Wednesday 10-05 23:59**.

In [1]:
# imports, no need to edit

import numpy as np
import pandas as pd

np.random.seed(42)

1. Explain the difference between a vector and matrix in NumPy in one sentence.

A matrix is more than one dimensional array but a vector is one dimensional array

2. Construct a NumPy Array from a list of 10 elements.

In [4]:
# YOUR CODE HERE
array = np.arange(1,11,1)
print(array)

[ 1  2  3  4  5  6  7  8  9 10]


3. Construct a 10x10 matrix filled with '0's of the integer data type.

In [6]:
# YOUR CODE HERE
np.zeros((10,10),dtype="int8")

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

4. Construct a 10x10 matrix filled with '1's, data type float.

In [8]:
# YOUR CODE HERE
np.ones((10,10),dtype="float32")

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)

5. Construct a 10x10 matrix filled with '9's of the integer data type.

In [14]:
# YOUR CODE HERE
print(np.full((10,10),9))

# another way

np.ones((10,10),dtype="int8")*9

[[9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]]


array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]], dtype=int8)

6. Construct a one-dimensional array with values between 5 and 25 that jumps with steps of 3 (`[5, 8, ...]`)

In [18]:
# YOUR CODE HERE
arr = np.arange(5,25,3)
arr

array([ 5,  8, 11, 14, 17, 20, 23])

7. Create an array of size 30 with evenly spaced values between -1 and 1.

In [25]:
# YOUR CODE HERE
data = np.linspace(-1,1,30)
data

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

8. Construct a 5x6 matrix with integers from 0 to 30.

In [27]:
# YOUR CODE HERE
np.random.randint(0,30,size=(5,6))

array([[ 6, 19, 28, 14, 10,  7],
       [28, 20,  6, 25, 18, 22],
       [10, 10, 23, 20,  3,  7],
       [23,  2, 21, 20,  1, 23],
       [11, 29,  5,  1, 27, 20]])

9. Create an array of 30 random integers and sort it in ascending order.

In [48]:
# YOUR CODE HERE
a = np.random.randint(30,size=30)
b=np.sort(a)
b

array([ 0,  0,  6,  7,  7,  8,  8, 10, 11, 12, 12, 12, 14, 14, 15, 16, 17,
       18, 20, 20, 23, 23, 23, 24, 24, 25, 27, 27, 27, 28])

10. Construct a 5x10 matrix filled with the value 1 at each location. Print the following details about this matrix:
- number of elements
- shape of the matrix
- the data type (using numpy methods)


In [55]:
# YOUR CODE HERE
a = np.ones((5,10))
print(f" the number of elements is {a.size}")
print(f" the shape of the matrix is {a.shape}")
print(f" the data type of elements is {a.dtype}")


 the number of elements is 50
 the shape of the matrix is (5, 10)
 the data type of elements is float64


11. Construct a 3x4x7 matrix with random integer values between 0 and 10 (a 3D matrix will be created).


In [56]:
# YOUR CODE HERE
np.random.randint(0,10,size=(3,4,7))

array([[[2, 2, 0, 4, 9, 6, 9],
        [8, 6, 8, 7, 1, 0, 6],
        [6, 7, 4, 2, 7, 5, 2],
        [0, 2, 4, 2, 0, 4, 9]],

       [[6, 6, 8, 9, 9, 2, 6],
        [0, 3, 3, 4, 6, 6, 3],
        [6, 2, 5, 1, 9, 8, 4],
        [5, 3, 9, 6, 8, 6, 0]],

       [[0, 8, 8, 3, 8, 2, 6],
        [5, 7, 8, 4, 0, 2, 9],
        [7, 5, 7, 8, 3, 0, 0],
        [9, 3, 6, 1, 2, 0, 4]]])

12. Create an array of 20 random integers and reshape it into a 4x5 matrix.

In [62]:
# YOUR CODE HERE
arr = np.random.randint(15,size=20)
np.reshape(arr,(4,5))

array([[ 1,  0, 13, 11,  4],
       [ 4, 10,  6,  8,  8],
       [ 2,  2,  2,  3,  7],
       [ 5,  7,  0,  7,  3]])

13. Construct a one-dimensional array by concetanating 4 separate one-dimensional arrays.

In [73]:
# YOUR CODE HERE
a=[1,2,3,4]
b=[1,2,3,4]
c=[1,2,3,4]
d=[1,2,3,4]

np.concatenate([a,b,c,d])
print()
print(np.concatenate([a,b,c,d], axis=0))


[1 2 3 4 1 2 3 4 1 2 3 4 1 2 3 4]


14. Create a vector of length 3 (3x1) and a matrix of size 3x3. Combine these two arrays on a
    column-by-column basis using numpy methods.


In [96]:
vec1 = np.array([1,2,3])
vec2 = np.reshape(vec1,(3,1))
print(vec2)

print()
mat = np.array([[1,2,3],[1,2,3],[1,2,3]])
print(mat)

print()

# concatenate to an existing row

com = np.concatenate((mat,vec2),axis=1)
print(com)
print()

####another   when concatenating take in consideration the axis of matrix should be the same as the axis of vector
# concat to an existing column
vec1 = np.array([1, 2, 3])
vec1 = np.reshape(vec1, (1, 3))
print(vec1)
print()
mat1 = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
new = np.concatenate((mat,vec1),axis=0)
print(new)


[[1]
 [2]
 [3]]

[[1 2 3]
 [1 2 3]
 [1 2 3]]

[[1 2 3 1]
 [1 2 3 2]
 [1 2 3 3]]

[[1 2 3]]

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [11]:
np.argmax(b)

5

15. What is the difference between "axis=1" and "axis=0" in Numpy functions? 

axis=1 means accross columns and axis=0 means accross rows

16. Create a random 1D vector with 20 elements. Find the 3rd, 5th and 7th elements of this vector.


In [104]:
vec = np.random.rand(20)
vec[[2,4,6]]

array([0.51832965, 0.74076862, 0.70248408])

17. Create a random vector with 10 elements and replace the 4th element of this array with a different number.

In [108]:
# YOUR CODE HERE

vec = np.random.rand(10)
vec[[3]]= 5
vec


array([0.07845638, 0.02535074, 0.96264841, 5.        , 0.69597421,
       0.40895294, 0.17329432, 0.15643704, 0.2502429 , 0.54922666])

18. Look up the concepts of *diagonal matrix* and *trace matrix* online and write a small explanation about what they are.

https://www.youtube.com/watch?v=ugPcTQl83lU&ab_channel=LadislauFernandes


YOUR ANSWER HERE

19. Create a 5x5 diagonal matrix with elements of your choosing. What are the indexes of the diagonal?


In [112]:
# YOUR CODE HERE
mat1 = np.array([[1, 2, 3], [1, 5, 3], [1, 2, 7]])
np.diagonal(mat1)   
np.trace(mat1)

13

20. Create a vector that ranges from 10 to 20. Print the values from the 3rd index to the last index.


In [120]:
# YOUR CODE HERE
vec = np.arange(10,21)
vec[3:]

array([13, 14, 15, 16, 17, 18, 19, 20])

21. Construct a 10x10 matrix with random elements and perform the following indexing tasks on it. Each task should be a single indexing operation.
 - Retrieve column 5 of row 3. Moreover;
 - Retrieve all elements of column 5.
 - Retrieve the 2nd row of all columns.
 - Retrieve row 2 through 7 of all columns.
 - Retrieve values with row index 2 to 5 and column index 3 to 7.
 - Retrieve the values from row index 5 to the end and column index from the top to 4.
 - Replace the value corresponding to the 5th row and the 5th column with your year of birth.

In [150]:
# YOUR CODE HERE
np.random.seed(42)
mat = np.random.rand(10,10)
print(mat)
print(mat[3,5])
print(mat[:,5])
print(mat[2:8, :])
print(mat[2:8, :])
print(mat[2:6, 3:8])
print(mat[5:, -1:5])
mat[5,5] = 1998
print(mat)


[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
  0.05808361 0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264 0.21233911 0.18182497 0.18340451
  0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184 0.45606998 0.78517596
  0.19967378 0.51423444 0.59241457 0.04645041]
 [0.60754485 0.17052412 0.06505159 0.94888554 0.96563203 0.80839735
  0.30461377 0.09767211 0.68423303 0.44015249]
 [0.12203823 0.49517691 0.03438852 0.9093204  0.25877998 0.66252228
  0.31171108 0.52006802 0.54671028 0.18485446]
 [0.96958463 0.77513282 0.93949894 0.89482735 0.59789998 0.92187424
  0.0884925  0.19598286 0.04522729 0.32533033]
 [0.38867729 0.27134903 0.82873751 0.35675333 0.28093451 0.54269608
  0.14092422 0.80219698 0.07455064 0.98688694]
 [0.77224477 0.19871568 0.00552212 0.81546143 0.70685734 0.72900717
  0.77127035 0.07404465 0.35846573 0.11586906]
 [0.86310343 0.62329813 0.33089802 0.06355835 0.31098232 0.32518332
  0.72960618

22. Construct a one-dimensional array from 0 to 50 jumping with steps of 5 (`[5, 10, ...]`). Use the numpy methods to perform the following tasks;
- Print all values greater than 20.
- Print all values less than 30.
- How many values are 33 in it?
- Multiply all the elements of the created array by 5.

In [158]:
# YOUR CODE HERE
arr = np.arange(0,51,10)
arr

print(arr[arr > 20])
print(arr[arr < 30])
print(np.size(arr[arr >= 33]))
print(arr*5)

[30 40 50]
[ 0 10 20]
2
[  0  50 100 150 200 250]


23. Construct an array of 50 random floats between 0 and 1 and take the average. Moreover;
- Get the standard deviation.
- Get the variance.
- Take the median.
- Find the smallest value.
- Find the largest value.

In [163]:
# YOUR CODE HERE

vec = np.random.rand(50)
vec
print(np.mean(vec))
print(np.std(vec))
print(np.var(vec))
print(np.min(vec))
print(np.max(vec))


0.45708518883345484
0.27306715205443444
0.07456566953111961
0.014393488629755868
0.9758520794625346


24. What are the differences between Pandas Series and NumPy arrays?

series are dictionary based and includes an index

25. Create a 5-element series with different data types, with an index of capital letters.

In [169]:
# YOUR CODE HERE
import pandas as pd
print(pd.Series([1, "Abdu", 15],index=["A","B","C"]))

print()
print(pd.DataFrame({"name":["Abd","john","jack","jane"], "age":[15,16,17,18]},index=["A","B","C","D"]))

A       1
B    Abdu
C      15
dtype: object

   name  age
A   Abd   15
B  john   16
C  jack   17
D  jane   18


26. Create a 5-element dictionary with keys as country names and values as capitals and turn it into a series. An example: ` "france" : "paris"`).

In [170]:
# YOUR CODE HERE
pd.Series({"Yemen":"Sana'a","Saudi Arabia":"Ryadh","Netherlands":"Amsterdam","United Arab Emirates":"Abudhabi "})

Yemen                      Sana'a
Saudi Arabia                Ryadh
Netherlands             Amsterdam
United Arab Emirates    Abudhabi 
dtype: object

27. Create a random vector with 10 elements.
- Convert the vector to series and with strings as indeces. For example, a,b,c,d,e,f,g..
- Retrieve the 3rd element of the series using the index name (for example: c).
- Retrieve the 1st element of the series using the index number.
- Access the 2nd and 7th elements of the series at the same time, using the index name. (Example: values corresponding to index b and g)

In [176]:
# YOUR CODE HERE
ser = pd.Series(np.random.rand(10),index=["A","B","C","D","E","F","G","H","I","J"])
print(ser)
print(ser[0])
print(ser["A"])
print(ser[["B","G"]])


A    0.103124
B    0.902553
C    0.505252
D    0.826457
E    0.320050
F    0.895523
G    0.389202
H    0.010838
I    0.905382
J    0.091287
dtype: float64
0.10312386883593261
0.10312386883593261
B    0.902553
G    0.389202
dtype: float64


28. Create two 5-element series with elements of your choice with default index.
- Combine the series you have created.
- Arrange the index of the resulting concatenated 10-element series from 1 to 10.

In [ ]:
# YOUR CODE HERE

**Bonus homework**:


Generate two 20x20 matrices with values between 0 and 1 randomly in a loop and take the difference of these
matrices. Repeat this process until all elements on the diagonal of the difference matrix
is between -0.1 and 0.1. When the desired matrix is found, let the program stop
and print the total number of cycles, how long it took, and the desired matrix
with print.


Tip: Finding the 20 x 20 matrix can take hours. Therefore, to test the accuracy
of your algorithm, you can first try it on small matrices such as 4x4, 5x5. And
you can try the latest 20x20 by increasing the number of matrix. (You can do
the matrix generation with the np.random.random((a,b)) function. It generates
an array of desired sizes between 0-1.)


In [8]:
# YOUR CODE HERE
import numpy as np
np.random.seed(42)
import time

size = 10

# record how long the while loop takes
start = time.time()

while True:
    # generate two random matrices of size 3x3
    a = np.random.random((size, size))
    b = np.random.random((size, size))

    diff = np.abs(a - b)
    # get diagonal of diff
    if np.all(np.diag(diff) <= 0.1):
        print("Found a match!")
        print("matrix 1:")
        print(a)
        print("matrix 2:")
        print(b)
        print("diagonal of diff:")
        print(np.diagonal(diff))
        break

# stop time
end = time.time()
print("Time taken: ", end - start)


[[0.80203982 0.30776679 0.96514057 0.22254882 0.96082357 0.88386248
  0.70451455 0.81831221 0.14548417 0.8959089 ]
 [0.98036683 0.14353201 0.28529909 0.69382485 0.60194746 0.475862
  0.31297111 0.97058358 0.17919567 0.15907398]
 [0.41137242 0.48203334 0.46616916 0.76720021 0.29136543 0.0795811
  0.78117109 0.12738464 0.68651872 0.39496577]
 [0.54496983 0.37466624 0.0617913  0.53042882 0.40448796 0.76969605
  0.20853571 0.51940513 0.91002657 0.00812047]
 [0.51407471 0.65924698 0.27077373 0.26043534 0.87028382 0.48404125
  0.11449501 0.35794764 0.08981719 0.08823397]
 [0.38782498 0.68402206 0.11227034 0.50878429 0.48766131 0.12199372
  0.95849971 0.98251215 0.55170378 0.59825786]
 [0.41522148 0.70202938 0.21248676 0.22896877 0.15433878 0.25010281
  0.46566852 0.06914628 0.39681494 0.55999141]
 [0.41197287 0.69454831 0.32287117 0.96678505 0.83378521 0.7331555
  0.70858667 0.12600876 0.34546425 0.00619238]
 [0.52984152 0.37588775 0.56028108 0.05727417 0.24793042 0.68294765
  0.52578849 0.6