## Data Manipulation module
### Homework assignment 1

Welcome to the first homework assignment of the data manipulation module. In this assignment you will be working with NumPy and Pandas Series. The goal of this assignment is to get you familiar with these libraries and data types.

### Instructions
Read the exercises carefully and implement the requested functionality. Add your code in the cells provided with `YOUR CODE HERE` or `YOUR ANSWER HERE`. You can add cells if you need to. **Make sure to use NumPy methods** to find your answers. In some cases you might be able to read the answer, but we want to see you using the NumPy methods.

### Hand-in
To hand in your assignment, fork this notebook and commit your changes, then make a pull request to the original repository. The deadline for handing in the assignment is **Wednesday 10-05 23:59**.

In [1]:
# imports, no need to edit

import numpy as np
import pandas as pd

np.random.seed(42)

1. Explain the difference between a vector and matrix in NumPy in one sentence.

YOUR ANSWER HERE
A vector is an array with a single dimension (there's no difference between row and column vectors), while a matrix refers to an array with two dimensions

2. Construct a NumPy Array from a list of 10 elements.

In [3]:
# YOUR CODE HERE
list1 = range(10)
matrix = np.array(list1)
print(list1)

range(0, 10)


3. Construct a 10x10 matrix filled with '0's of the integer data type.

In [10]:
# YOUR CODE HERE
matrix = np.zeros((10,10))
matrix = matrix.astype(int)
print(matrix.dtype)
matrix

int32


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

4. Construct a 10x10 matrix filled with '1's, data type float.

In [11]:
# YOUR CODE HERE
matrix = np.ones((10,10))
print(matrix.dtype)
matrix

float64


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

5. Construct a 10x10 matrix filled with '9's of the integer data type.

In [13]:
# YOUR CODE HERE
matrix = np.ones((10,10))
matrix = matrix * 9 
matrix = matrix.astype(int)
print(matrix.dtype)
matrix

int32


array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

6. Construct a one-dimensional array with values between 5 and 25 that jumps with steps of 3 (`[5, 8, ...]`)

In [15]:
# YOUR CODE HERE
array = range(5,25,3)
array = np.array(array)
array

array([ 5,  8, 11, 14, 17, 20, 23])

7. Create an array of size 30 with evenly spaced values between -1 and 1.

In [44]:

x=np.random.randint(3, size=(5,6))
x1 = x.mean(axis=1)
x2 = x - x1.reshape(-1,1)
print(x2)

[[ 0.          0.         -1.          0.          1.          0.        ]
 [ 0.33333333  1.33333333  0.33333333 -0.66666667 -0.66666667 -0.66666667]
 [ 0.66666667 -0.33333333 -1.33333333  0.66666667 -0.33333333  0.66666667]
 [-0.66666667 -0.66666667 -0.66666667  1.33333333  1.33333333 -0.66666667]
 [ 1.16666667 -0.83333333 -0.83333333  0.16666667  1.16666667 -0.83333333]]


8. Construct a 5x6 matrix with integers from 0 to 30.

In [51]:
# YOUR CODE HERE
# array = np.random.randint(0,30 ,size=(5 , 6))
# array
array = np.arange(30)
array = array.reshape(5,6)
array

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

9. Create an array of 30 random integers and sort it in ascending order.

In [52]:
# YOUR CODE HERE
array = np.random.randint(100, size=(30))
print(array)
print(np.sort(array))

[12 11 94 45  1 34 86 80 89  7 92 25 73 89 33  6 67 57 74 28 35 88 20 35
  9 72 23 63 98 48]
[ 1  6  7  9 11 12 20 23 25 28 33 34 35 35 45 48 57 63 67 72 73 74 80 86
 88 89 89 92 94 98]


10. Construct a 5x10 matrix filled with the value 1 at each location. Print the following details about this matrix:
- number of elements
- shape of the matrix
- the data type (using numpy methods)


In [59]:
# YOUR CODE HERE
array = np.ones((5,10))
print(array)
print(array.size)
print(array.shape)
print(array.dtype)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
50
(5, 10)
float64


11. Construct a 3x4x7 matrix with random integer values between 0 and 10 (a 3D matrix will be created).


In [67]:
# YOUR CODE HERE
matrix = np.random.randint(10,size=(3,4,7))
print(matrix.dtype)
print(matrix.shape)
matrix

int32
(3, 4, 7)


array([[[5, 3, 9, 1, 7, 5, 4],
        [8, 0, 4, 5, 4, 5, 5],
        [6, 3, 7, 6, 8, 6, 2],
        [2, 7, 4, 3, 7, 5, 1]],

       [[3, 3, 5, 5, 0, 7, 5],
        [2, 8, 1, 7, 9, 2, 4],
        [5, 9, 5, 3, 2, 3, 0],
        [3, 0, 0, 9, 5, 4, 3]],

       [[2, 0, 5, 1, 7, 9, 4],
        [6, 9, 1, 7, 1, 3, 0],
        [4, 8, 0, 8, 7, 5, 6],
        [2, 0, 4, 1, 4, 7, 8]]])

12. Create an array of 20 random integers and reshape it into a 4x5 matrix.

In [73]:
# YOUR CODE HERE

random_array = np.random.randint(0,20,20)
random_array = random_array.reshape(4,5)
print(random_array.shape)
random_array


(4, 5)


array([[ 9,  0,  5, 12, 14],
       [ 3, 12, 19, 14,  7],
       [ 4, 14,  3, 11, 12],
       [ 1, 18, 18,  3,  3]])

13. Construct a one-dimensional array by concetanating 4 separate one-dimensional arrays.

In [89]:
# YOUR CODE HERE

list1 = range(4)
array1 = np.array((list1))
array2 = np.array((list1))
array3 = np.array((list1))
array4 = np.array((list1))
print(array1.shape)
print(array1, array2,array3,array4)
print(np.concatenate((array1,array2,array3,array4),axis=0))

(4,)
[0 1 2 3] [0 1 2 3] [0 1 2 3] [0 1 2 3]
[0 1 2 3 0 1 2 3 0 1 2 3 0 1 2 3]


14. Create a vector of length 3 (3x1) and a matrix of size 3x3. Combine these two arrays on a
    column-by-column basis using numpy methods.


In [98]:
a = np.array([1, 2, 3]).reshape(-1, 1)
b = np.random.randint(0, 10, (3, 3))
c = np.concatenate((a,b),axis=1)
print(c)

[[1 4 7 0]
 [2 0 5 9]
 [3 1 4 0]]
(3, 4)


In [11]:
np.argmax(b)

5

15. What is the difference between "axis=1" and "axis=0" in Numpy functions? 

YOUR ANSWER HERE

the first running vertically downwards across rows (axis 0), and the second running horizontally across columns (axis 1).

16. Create a random 1D vector with 20 elements. Find the 3rd, 5th and 7th elements of this vector.


In [132]:
# YOUR CODE HERE
vector = np.random.randint(20,size=(20))
vector
print(vector[2],vector[5],vector[7])


12 5 15


array([ 1,  7, 12, 12,  0,  5, 18, 15,  7,  0, 15,  8, 12, 10, 12,  9,  3,
        5,  6,  4])

17. Create a random vector with 10 elements and replace the 4th element of this array with a different number.

In [149]:
# YOUR CODE HERE
vector = np.random.randint(10,size=(10))
print(vector)
vector[3] = 8
print(vector)

[2 5 8 5 8 6 8 1 7 7]
[2 5 8 8 8 6 8 1 7 7]


18. Look up the concepts of *diagonal matrix* and *trace matrix* online and write a small explanation about what they are.


YOUR ANSWER HERE

A diagonal matrix is a matrix (usually a square matrix of order n) filled with values on the main diagonal and zeros everywhere else.

Trace of Matrix is the sum of main diagonal elements of the matrix.



19. Create a 5x5 diagonal matrix with elements of your choosing. What are the indexes of the diagonal?


In [160]:
# YOUR CODE HERE
x = np.diag([1, 2, 3, 4, 5])
print(x.diagonal())
di = np.diag_indices(5)
print(x)
print(di)

[1 2 3 4 5]
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
(array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4]))


20. Create a vector that ranges from 10 to 20. Print the values from the 3rd index to the last index.


In [165]:
# YOUR CODE HERE
list1 = range(10 , 20)
vector = np.array(list1)
print(vector)
vector[2:]

[10 11 12 13 14 15 16 17 18 19]


array([12, 13, 14, 15, 16, 17, 18, 19])

21. Construct a 10x10 matrix with random elements and perform the following indexing tasks on it. Each task should be a single indexing operation.
 - Retrieve column 5 of row 3. Moreover;
 - Retrieve all elements of column 5.
 - Retrieve the 2nd row of all columns.
 - Retrieve row 2 through 7 of all columns.
 - Retrieve values with row index 2 to 5 and column index 3 to 7.
 - Retrieve the values from row index 5 to the end and column index from the top to 4.
 - Replace the value corresponding to the 5th row and the 5th column with your year of birth.

In [199]:
# YOUR CODE HERE
matrix = np.random.randint(100 , size=(10,10))
print(matrix)
print(matrix[4,2])
print(matrix[:,4])
print(matrix[1,:])
print(matrix[1:7,:])
print(matrix[2:5,3:7])
print(matrix[5:,:])
print(matrix[:,:4])
x = matrix[5,:] = [4,1,2,3,4,5,6,7,8,9]
print(x)
y = matrix[:,5] = [1,9,9,8,0,5,0,1,0,0]
print(y)

[[ 3 95 22 69 87 83 83 75 32 27]
 [ 7  0 36 62 21 69 20 95 34 78]
 [ 4 59 45 49 47  5 88 55 58 28]
 [70 76 17  1  7 74 96 53 37 47]
 [26 19 11 42 60 30 90 95 60 73]
 [66 90 34 94 14 15 12 34 74 58]
 [20 53 74 29 47 34 85 37 30 77]
 [23 48 95 99 31 54 78 57 98  2]
 [79 68 84  9 82 24 67 60 28 18]
 [42 65 73 60 42 24 19 47 82 86]]
11
[87 21 47  7 60 14 47 31 82 42]
[ 7  0 36 62 21 69 20 95 34 78]
[[ 7  0 36 62 21 69 20 95 34 78]
 [ 4 59 45 49 47  5 88 55 58 28]
 [70 76 17  1  7 74 96 53 37 47]
 [26 19 11 42 60 30 90 95 60 73]
 [66 90 34 94 14 15 12 34 74 58]
 [20 53 74 29 47 34 85 37 30 77]]
[[49 47  5 88]
 [ 1  7 74 96]
 [42 60 30 90]]
[[66 90 34 94 14 15 12 34 74 58]
 [20 53 74 29 47 34 85 37 30 77]
 [23 48 95 99 31 54 78 57 98  2]
 [79 68 84  9 82 24 67 60 28 18]
 [42 65 73 60 42 24 19 47 82 86]]
[[ 3 95 22 69]
 [ 7  0 36 62]
 [ 4 59 45 49]
 [70 76 17  1]
 [26 19 11 42]
 [66 90 34 94]
 [20 53 74 29]
 [23 48 95 99]
 [79 68 84  9]
 [42 65 73 60]]
[4, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 9, 9,

22. Construct a one-dimensional array from 0 to 50 jumping with steps of 5 (`[5, 10, ...]`). Use the numpy methods to perform the following tasks;
- Print all values greater than 20.
- Print all values less than 30.
- How many values are 33 in it?
- Multiply all the elements of the created array by 5.

In [207]:
# YOUR CODE HERE
array = range(0,50,5)
array = np.array(array)
print(array)
great_than_20 = array[array > 20 ]
print(great_than_20)
less_than_30 = array[array < 30 ]
print(less_than_30)
##############

#############
multiply = array * 5 
print(multiply)

[ 0  5 10 15 20 25 30 35 40 45]
[25 30 35 40 45]
[ 0  5 10 15 20 25]
[  0  25  50  75 100 125 150 175 200 225]


23. Construct an array of 50 random floats between 0 and 1 and take the average. Moreover;
- Get the standard deviation.
- Get the variance.
- Take the median.
- Find the smallest value.
- Find the largest value.

In [216]:
# YOUR CODE HERE
array = np.random.uniform(low=0, high=1, size=(50,))
standard_deviation = np.std(array,axis=0)
print(standard_deviation)
variance = np.var(array)
print(variance)
median = np.median(array)
print(median)
main = np.amin(array)
print(main)
max = np.amax(array)
print(max)

0.28712942932383084
0.08244330918382876
0.5169997199265538
0.032659060784495875
0.9711509073682858


24. What are the differences between Pandas Series and NumPy arrays?

YOUR ANSWER HERE

the Numpy Array has an implicitly defined integer index used to access the values, the Pandas Series has an explicitly defined index associated with the values.

25. Create a 5-element series with different data types, with an index of capital letters.

In [220]:
# YOUR CODE HERE
import pandas as pd
list1 = [1,1.5,True,"A",[1,],(5,)]
index = ["A","B","C","D","E","F"]
series = pd.Series(list1,index=index)
print(series)

A       1
B     1.5
C    True
D       A
E     [1]
F    (5,)
dtype: object


26. Create a 5-element dictionary with keys as country names and values as capitals and turn it into a series. An example: ` "france" : "paris"`).

In [221]:
# YOUR CODE HERE
element = { 
    "Armenia":"Yerevan",
    "Australia":"Canberra",
    "Austria":"Vienna",
    "China":"Beijing",
    "Colombia":"Bogota",
}
series = pd.Series(element)
print(series)

Armenia       Yerevan
Australia    Canberra
Austria        Vienna
China         Beijing
Colombia       Bogota
dtype: object


27. Create a random vector with 10 elements.
- Convert the vector to series and with strings as indeces. For example, a,b,c,d,e,f,g..
- Retrieve the 3rd element of the series using the index name (for example: c).
- Retrieve the 1st element of the series using the index number.
- Access the 2nd and 7th elements of the series at the same time, using the index name. (Example: values corresponding to index b and g)

In [237]:
# YOUR CODE HERE
x = np.random.random(10)
print(x)
index = ['a','b','c','d','e','f','g','h','i','j']
series = pd.Series(x , index=index)
print(series)
print(series['b'])
print(series[0])
series[['b','g']]

[0.65942296 0.57780705 0.86610155 0.28943952 0.46768121 0.61938997
 0.41119048 0.42748645 0.33028467 0.56423182]
a    0.659423
b    0.577807
c    0.866102
d    0.289440
e    0.467681
f    0.619390
g    0.411190
h    0.427486
i    0.330285
j    0.564232
dtype: float64
0.5778070502510847
0.6594229620819976


b    0.577807
g    0.411190
dtype: float64

28. Create two 5-element series with elements of your choice with default index.
- Combine the series you have created.
- Arrange the index of the resulting concatenated 10-element series from 1 to 10.

In [257]:
# YOUR CODE HERE
data1 = np.array(['g', 'e', 'e', 'k', 's'])
data2 = np.array([1,2,3,4,5])
ser1 = pd.Series(data1)
ser2 = pd.Series(data2)
sorted1 = np.sort(ser1)
sorted2 = np.sort(ser2)
combine = pd.concat([ser1,ser2], axis=0)
# sorted = np.sort(combine)
# sorted = combine.sort_values(ascending=True, inplace=True)
print(combine)


0    g
1    e
2    e
3    k
4    s
0    1
1    2
2    3
3    4
4    5
dtype: object


**Bonus homework**:


Generate two 20x20 matrices with values between 0 and 1 randomly in a loop and take the difference of these
matrices. Repeat this process until all elements on the diagonal of the difference matrix
is between -0.1 and 0.1. When the desired matrix is found, let the program stop
and print the total number of cycles, how long it took, and the desired matrix
with print.


Tip: Finding the 20 x 20 matrix can take hours. Therefore, to test the accuracy
of your algorithm, you can first try it on small matrices such as 4x4, 5x5. And
you can try the latest 20x20 by increasing the number of matrix. (You can do
the matrix generation with the np.random.random((a,b)) function. It generates
an array of desired sizes between 0-1.)


In [291]:
import time

start = time.time()

while True : 
    array1 = np.random.uniform(low=0, high=1, size=(20,20))
    array2 = np.random.uniform(low=0, high=1, size=(20,20))
    # array = array1 - array2 
    # print(array)
    array = np.abs(array1 - array2)
    print(array)
    if np.all(np.diag(diff) <= 0.1):
        print("Matrix1 : ")
        print("*********************",array1,"*************************")
        print("Matrix : ")
        print("*********************",array2,"*************************")

        print(np.diagonal(diff))
        break

end = time.time()
print("Time taken: ", end - start)
print(array1.shape)




[[0.0756283  0.28644266 0.06993472 0.36858383 0.1694415  0.95814137
  0.25222779 0.49690116 0.18466206 0.19264768 0.03007757 0.01044325
  0.20547912 0.07606125 0.51257545 0.37337117 0.20552681 0.79968499
  0.49684901 0.03306688]
 [0.20648461 0.41079031 0.03134514 0.14939753 0.28209003 0.21976592
  0.54071614 0.48636027 0.04285391 0.381675   0.20249044 0.08770304
  0.68386927 0.16065693 0.47342746 0.14173766 0.01386907 0.64581514
  0.18594909 0.15696524]
 [0.44874312 0.30440533 0.09672673 0.20292446 0.42428177 0.31780437
  0.01111909 0.34217658 0.13361692 0.12431878 0.12469072 0.32729389
  0.72820791 0.16414813 0.21202915 0.05336546 0.48015389 0.34141566
  0.35614117 0.34550524]
 [0.08972943 0.18240685 0.10770822 0.58552976 0.23024587 0.44004248
  0.36764452 0.05710406 0.14814699 0.82779107 0.43223992 0.56640222
  0.07608416 0.18786412 0.2957664  0.18287589 0.54465448 0.72697366
  0.70908873 0.19653573]
 [0.46589932 0.09493405 0.22668747 0.39981207 0.2525164  0.63740928
  0.12849939 0.0