## Data Manipulation module
### Homework assignment 1

Welcome to the first homework assignment of the data manipulation module. In this assignment you will be working with NumPy and Pandas Series. The goal of this assignment is to get you familiar with these libraries and data types.

### Instructions
Read the exercises carefully and implement the requested functionality. Add your code in the cells provided with `YOUR CODE HERE` or `YOUR ANSWER HERE`. You can add cells if you need to. **Make sure to use NumPy methods** to find your answers. In some cases you might be able to read the answer, but we want to see you using the NumPy methods.

### Hand-in
To hand in your assignment, fork this notebook and commit your changes, then make a pull request to the original repository. The deadline for handing in the assignment is **Wednesday 10-05 23:59**.

In [3]:
# imports, no need to edit

import numpy as np
import pandas as pd

np.random.seed(42)

1. Explain the difference between a vector and matrix in NumPy in one sentence.

A vector is an array with a single dimension while a matrix refers to an array with two dimensions.

2. Construct a NumPy Array from a list of 10 elements.

In [4]:
lst_a = [3,5,12,3,9,7,0,23,4,8]
vect_a = np.array(lst_a)
print(vect_a)

[ 3  5 12  3  9  7  0 23  4  8]


3. Construct a 10x10 matrix filled with '0's of the integer data type.

In [5]:
zeros = np.zeros((10,10), dtype=np.int64)
print(zeros)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


4. Construct a 10x10 matrix filled with '1's, data type float.

In [6]:
ones = np.ones((10,10))
print(ones)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


5. Construct a 10x10 matrix filled with '9's of the integer data type.

In [7]:
nines = np.full((10,10), 9, dtype=np.int64)
print(nines)

[[9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]]


6. Construct a one-dimensional array with values between 5 and 25 that jumps with steps of 3 (`[5, 8, ...]`)

In [8]:
step3 = np.arange(5,25,3)
print(step3)

[ 5  8 11 14 17 20 23]


7. Create an array of size 30 with evenly spaced values between -1 and 1.

In [9]:
a =  np.linspace(-1,1, num = 30)
print(a)

[-1.         -0.93103448 -0.86206897 -0.79310345 -0.72413793 -0.65517241
 -0.5862069  -0.51724138 -0.44827586 -0.37931034 -0.31034483 -0.24137931
 -0.17241379 -0.10344828 -0.03448276  0.03448276  0.10344828  0.17241379
  0.24137931  0.31034483  0.37931034  0.44827586  0.51724138  0.5862069
  0.65517241  0.72413793  0.79310345  0.86206897  0.93103448  1.        ]


8. Construct a 5x6 matrix with integers from 0 to 30.

In [10]:
matrix = np.arange(0,30,1).reshape(5,6)
print(matrix)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


9. Create an array of 30 random integers and sort it in ascending order.

In [11]:
rn_arr= np.random.randint(100, size=30)
sorted_arr= np.sort(rn_arr)
print(sorted_arr)

[ 1  1  2 14 20 20 21 21 23 29 32 37 48 51 52 57 59 60 63 71 74 74 75 82
 86 87 87 88 92 99]


10. Construct a 5x10 matrix filled with the value 1 at each location. Print the following details about this matrix:
- number of elements
- shape of the matrix
- the data type (using numpy methods)


In [12]:
ones = np.ones((5,10))
print("Element count = ",np.size(ones))
print("Shape of the matrix = ",np.shape(ones))
print("Data type of the matrix elements = ",ones.dtype)

Element count =  50
Shape of the matrix =  (5, 10)
Data type of the matrix elements =  float64


11. Construct a 3x4x7 matrix with random integer values between 0 and 10 (a 3D matrix will be created).


In [13]:
arr= np.random.randint(10,size=(3,4,7))
print(arr)

[[[9 2 6 3 8 2 4]
  [2 6 4 8 6 1 3]
  [8 1 9 8 9 4 1]
  [3 6 7 2 0 3 1]]

 [[7 3 1 5 5 9 3]
  [5 1 9 1 9 3 7]
  [6 8 7 4 1 4 7]
  [9 8 8 0 8 6 8]]

 [[7 0 7 7 2 0 7]
  [2 2 0 4 9 6 9]
  [8 6 8 7 1 0 6]
  [6 7 4 2 7 5 2]]]


12. Create an array of 20 random integers and reshape it into a 4x5 matrix.

In [14]:
rn_arr= np.random.randint(100,size=20)
matrix45= rn_arr.reshape(4,5)
print(matrix45)

[[64 98 46 77  2]
 [ 0  4 89 13 26]
 [ 8 78 14 89 41]
 [76 50 62 95 51]]


13. Construct a one-dimensional array by concetanating 4 separate one-dimensional arrays.

In [15]:
a= np.random.randint(100, size=5)
b= np.random.randint(100, size=5)
c= np.random.randint(100, size=5)
d= np.random.randint(100, size=5)

e = np.concatenate((a,b,c,d))

print(e)

[95  3 93 22 14 42 28 35 12 31 70 58 85 27 65 41 44 61 56  5]


14. Create a vector of length 3 (3x1) and a matrix of size 3x3. Combine these two arrays on a
    column-by-column basis using numpy methods.


In [16]:
a = np.array([1, 2, 3]).reshape(-1, 1)
b = np.random.randint(0, 10, (3, 3))
print(a)
print(b)
c = np.hstack((b,a))
print(c)


[[1]
 [2]
 [3]]
[[3 9 6]
 [8 6 0]
 [0 8 8]]
[[3 9 6 1]
 [8 6 0 2]
 [0 8 8 3]]


In [17]:
np.argmax(b)

1

15. What is the difference between "axis=1" and "axis=0" in Numpy functions? 

Specifies the axis on which the functions should be calculated. If axis=0, the function is calculated for each column and the column results are obtained as a vector. If axis=1, the function is calculated for each row

16. Create a random 1D vector with 20 elements. Find the 3rd, 5th and 7th elements of this vector.


In [18]:
arr = np.random.randint(100, size=20)
print(arr)
print(arr[[2,4,6]])

[76  2 69 71 26  8 61 36 96 50 43 23 78 58 31 95 87 51 61 57]
[69 26 61]


17. Create a random vector with 10 elements and replace the 4th element of this array with a different number.

In [19]:
arr = np.random.randint(100, size=10)
print(arr)
arr[3]=35
print(arr)

[51 11 38  1  2 55 80 58  1  1]
[51 11 38 35  2 55 80 58  1  1]


18. Look up the concepts of *diagonal matrix* and *trace matrix* online and write a small explanation about what they are.


Diagonal matrix is a matrix in which the entries outside the main diagonal are all zero; the term usually refers to square matrices. Elements of the main diagonal can either be zero or nonzero.

The trace of a matrix is the sum of its main diagonal entries. For this operation, the matrix must be a square matrix.

19. Create a 5x5 diagonal matrix with elements of your choosing. What are the indexes of the diagonal?


In [20]:
size = 5
diagonal = np.random.randint(25, size = size)
matrix = np.diag(diagonal)
print(matrix)
print()
index_diag = np.diag_indices_from(matrix)
print(index_diag)


[[21  0  0  0  0]
 [ 0 22  0  0  0]
 [ 0  0  4  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]

(array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4]))


20. Create a vector that ranges from 10 to 20. Print the values from the 3rd index to the last index.


In [21]:
min, max = 10, 20
arr = (max - min)*np.random.random(size=20) + min
print(arr)
print(arr[3:])

[12.39561891 11.44894872 14.8945276  19.85650454 12.42055272 16.72135547
 17.61619615 12.37637544 17.28216349 13.67783133 16.32305831 16.33529711
 15.35774684 10.9028977  18.35302496 13.20780065 11.8651851  10.40775142
 15.90892943 16.77564362]
[19.85650454 12.42055272 16.72135547 17.61619615 12.37637544 17.28216349
 13.67783133 16.32305831 16.33529711 15.35774684 10.9028977  18.35302496
 13.20780065 11.8651851  10.40775142 15.90892943 16.77564362]


21. Construct a 10x10 matrix with random elements and perform the following indexing tasks on it. Each task should be a single indexing operation.
 - Retrieve column 5 of row 3. Moreover;
 - Retrieve all elements of column 5.
 - Retrieve the 2nd row of all columns.
 - Retrieve row 2 through 7 of all columns.
 - Retrieve values with row index 2 to 5 and column index 3 to 7.
 - Retrieve the values from row index 5 to the end and column index from the top to 4.
 - Replace the value corresponding to the 5th row and the 5th column with your year of birth.

In [22]:
matrix = np.random.randint(100,size=(10,10))
print(matrix)
print()
print(matrix[3,5])
print()
print(matrix[:,5])
print()
print(matrix[2,:])
print()
print(matrix[2:7,:])
print()
print(matrix[2:5,3:7])
print()
print(matrix[5:,:4])
print()
matrix[5,5]=1976
print(matrix)
print()

[[18 89 66 18 19 95 70 51 32 39]
 [38 81  0 10 91 56 88 49 22 30]
 [93 41 98  6 15 89 59  1  0 47]
 [11 68 36 31  8 98 18 47 79  2]
 [19 23 53 32 23 74 71 35 37 83]
 [98 88 98 24 92 17 81 65 53 34]
 [79 60 40 99 32 67 32 13 20 47]
 [19  7  6 66 16 32 47 75 58 85]
 [21 29 37 50 53  7 26 26 97 20]
 [29 96 27 63 96 68 60 47 18  3]]

98

[95 56 89 98 74 17 67 32  7 68]

[93 41 98  6 15 89 59  1  0 47]

[[93 41 98  6 15 89 59  1  0 47]
 [11 68 36 31  8 98 18 47 79  2]
 [19 23 53 32 23 74 71 35 37 83]
 [98 88 98 24 92 17 81 65 53 34]
 [79 60 40 99 32 67 32 13 20 47]]

[[ 6 15 89 59]
 [31  8 98 18]
 [32 23 74 71]]

[[98 88 98 24]
 [79 60 40 99]
 [19  7  6 66]
 [21 29 37 50]
 [29 96 27 63]]

[[  18   89   66   18   19   95   70   51   32   39]
 [  38   81    0   10   91   56   88   49   22   30]
 [  93   41   98    6   15   89   59    1    0   47]
 [  11   68   36   31    8   98   18   47   79    2]
 [  19   23   53   32   23   74   71   35   37   83]
 [  98   88   98   24   92 1976   81   65 

22. Construct a one-dimensional array from 0 to 50 jumping with steps of 5 (`[5, 10, ...]`). Use the numpy methods to perform the following tasks;
- Print all values greater than 20.
- Print all values less than 30.
- How many values are 33 in it?
- Multiply all the elements of the created array by 5.

In [23]:
arr = np.arange(0,50,5)
print(arr)
print()
print(arr[arr>20])
print()
print(arr[arr<30])
print()
print(arr[arr>33])
print()
arr *= 5 
print(arr)
print()

[ 0  5 10 15 20 25 30 35 40 45]

[25 30 35 40 45]

[ 0  5 10 15 20 25]

[35 40 45]

[  0  25  50  75 100 125 150 175 200 225]



23. Construct an array of 50 random floats between 0 and 1 and take the average. Moreover;
- Get the standard deviation.
- Get the variance.
- Take the median.
- Find the smallest value.
- Find the largest value.

In [24]:
arr = np.random.random(50)
std = np.std(arr)
var = np.var(arr)
median = np.median(arr)
min = np.min(arr)
max = np.max(arr)
print(arr)
print(std)
print(var)
print(median)
print(min)
print(max)

[0.02431597 0.6454723  0.17711068 0.94045858 0.95392858 0.91486439
 0.3701587  0.01545662 0.92831856 0.42818415 0.96665482 0.96361998
 0.85300946 0.29444889 0.38509773 0.85113667 0.31692201 0.16949275
 0.55680126 0.93615477 0.6960298  0.57006117 0.09717649 0.61500723
 0.99005385 0.14008402 0.51832965 0.87737307 0.74076862 0.69701574
 0.70248408 0.35949115 0.29359184 0.80936116 0.81011339 0.86707232
 0.91324055 0.5113424  0.50151629 0.79829518 0.64996393 0.70196688
 0.79579267 0.89000534 0.33799516 0.37558295 0.09398194 0.57828014
 0.03594227 0.46559802]
0.2948247189494498
0.08692161490362206
0.6302397613031687
0.015456616528867428
0.9900538501042633


24. What are the differences between Pandas Series and NumPy arrays?

        Pandas                                                  Numpy
Tabular data                                              Numerical data 
Data frame and Series                                     Arrays
consumes more memory                                      memory efficient
better performance over 500K rows	                  better performance below 50K rows
Indexing of the pandas series is very slow 	          Indexing of numpy Arrays is very fast.
It has a higher industry application.	                  It has a lower industry application.

25. Create a 5-element series with different data types, with an index of capital letters.

In [25]:
series = pd.Series({'A':123, 'B':'name','C':'password', 'D':True,'E':13.2 })
print(series)

A         123
B        name
C    password
D        True
E        13.2
dtype: object


26. Create a 5-element dictionary with keys as country names and values as capitals and turn it into a series. An example: ` "france" : "paris"`).

In [26]:
series = pd.Series({'Germany':'Berlin', 'Netherland':'Amsterdam','Norway':'OSlo', 'Denmark':'Kopenhag', 'France':'Paris'})
print(series)

Germany          Berlin
Netherland    Amsterdam
Norway             OSlo
Denmark        Kopenhag
France            Paris
dtype: object


27. Create a random vector with 10 elements.
- Convert the vector to series and with strings as indeces. For example, a,b,c,d,e,f,g..
- Retrieve the 3rd element of the series using the index name (for example: c).
- Retrieve the 1st element of the series using the index number.
- Access the 2nd and 7th elements of the series at the same time, using the index name. (Example: values corresponding to index b and g)

In [37]:
arr = np.random.randint(10, size=10)
index = ['a', 'b', 'c', 'd', 'e','f', 'g', 'h', 'i', 'j']
series = pd.Series(arr, index)
print(series)
print()
print(series['c'])
print()
print(series[0])
print()
print(series[['b', 'g']])

a    9
b    1
c    2
d    1
e    2
f    6
g    0
h    9
i    7
j    9
dtype: int32

2

9

b    1
g    0
dtype: int32


28. Create two 5-element series with elements of your choice with default index.
- Combine the series you have created.
- Arrange the index of the resulting concatenated 10-element series from 1 to 10.

In [44]:
ser1 = pd.Series(np.random.random(5))
ser2 = pd.Series(np.random.random(5))
ser3 = pd.concat([ser1, ser2])
ser3.index=np.arange(0,10)
print()
print(ser3)



0    0.396652
1    0.891897
2    0.146605
3    0.513326
4    0.233228
5    0.581305
6    0.863139
7    0.880360
8    0.236685
9    0.907694
dtype: float64


**Bonus homework**:


Generate two 20x20 matrices with values between 0 and 1 randomly in a loop and take the difference of these
matrices. Repeat this process until all elements on the diagonal of the difference matrix
is between -0.1 and 0.1. When the desired matrix is found, let the program stop
and print the total number of cycles, how long it took, and the desired matrix
with print.


Tip: Finding the 20 x 20 matrix can take hours. Therefore, to test the accuracy
of your algorithm, you can first try it on small matrices such as 4x4, 5x5. And
you can try the latest 20x20 by increasing the number of matrix. (You can do
the matrix generation with the np.random.random((a,b)) function. It generates
an array of desired sizes between 0-1.)


In [29]:
# YOUR CODE HERE
import numpy as np
np.random.seed(42)
import time

size= 10
cycles= 0

# record how long the while loop takes
start = time.time()

while True:
    # generate two random matrices of size 3x3
    a = np.random.random((size, size))
    b = np.random.random((size, size))

    cycles += 1
    diff = np.abs(a - b)
    # get diagonal of diff
    if np.all(np.diag(diff) <= 0.1):
        print("Found a match!")
        print("matrix 1:")
        print(a)
        print("matrix 2:")
        print(b)
        print("diagonal of diff:")
        print(np.diagonal(a-b))
        break

# stop time
end = time.time()
print(f"Time taken: {end - start}")
print(f"Match found at {cycles}. iteration")


Found a match!
matrix 1:
[[0.80203982 0.30776679 0.96514057 0.22254882 0.96082357 0.88386248
  0.70451455 0.81831221 0.14548417 0.8959089 ]
 [0.98036683 0.14353201 0.28529909 0.69382485 0.60194746 0.475862
  0.31297111 0.97058358 0.17919567 0.15907398]
 [0.41137242 0.48203334 0.46616916 0.76720021 0.29136543 0.0795811
  0.78117109 0.12738464 0.68651872 0.39496577]
 [0.54496983 0.37466624 0.0617913  0.53042882 0.40448796 0.76969605
  0.20853571 0.51940513 0.91002657 0.00812047]
 [0.51407471 0.65924698 0.27077373 0.26043534 0.87028382 0.48404125
  0.11449501 0.35794764 0.08981719 0.08823397]
 [0.38782498 0.68402206 0.11227034 0.50878429 0.48766131 0.12199372
  0.95849971 0.98251215 0.55170378 0.59825786]
 [0.41522148 0.70202938 0.21248676 0.22896877 0.15433878 0.25010281
  0.46566852 0.06914628 0.39681494 0.55999141]
 [0.41197287 0.69454831 0.32287117 0.96678505 0.83378521 0.7331555
  0.70858667 0.12600876 0.34546425 0.00619238]
 [0.52984152 0.37588775 0.56028108 0.05727417 0.24793042 0.