## Data Manipulation module
### Homework assignment 1

Welcome to the first homework assignment of the data manipulation module. In this assignment you will be working with NumPy and Pandas Series. The goal of this assignment is to get you familiar with these libraries and data types.

### Instructions
Read the exercises carefully and implement the requested functionality. Add your code in the cells provided with `YOUR CODE HERE` or `YOUR ANSWER HERE`. You can add cells if you need to. **Make sure to use NumPy methods** to find your answers. In some cases you might be able to read the answer, but we want to see you using the NumPy methods.

### Hand-in
To hand in your assignment, fork this notebook and commit your changes, then make a pull request to the original repository. The deadline for handing in the assignment is **Wednesday 10-05 23:59**.

In [1]:
# imports, no need to edit

import numpy as np
import pandas as pd

np.random.seed(42)

1. Explain the difference between a vector and matrix in NumPy in one sentence.

A vector in NumPy is a one-dimensional array like 1x5, while a matrix is a two-dimensional array like 5x5.YOUR ANSWER HERE

2. Construct a NumPy Array from a list of 10 elements.

In [5]:
# YOUR CODE HERE
myList=[1,2,3]
myArray=np.array(myList)
myArray

array([1, 2, 3])

3. Construct a 10x10 matrix filled with '0's of the integer data type.

In [8]:
# YOUR CODE HERE
np.zeros((5,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

4. Construct a 10x10 matrix filled with '1's, data type float.

In [9]:
# YOUR CODE HERE
np.ones((10,10), dtype=float)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

5. Construct a 10x10 matrix filled with '9's of the integer data type.

In [11]:
# YOUR CODE HERE
np.ones((10,10), dtype=float)*9
np.full((10, 10), 9, dtype=int)

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

6. Construct a one-dimensional array with values between 5 and 25 that jumps with steps of 3 (`[5, 8, ...]`)

In [12]:
# YOUR CODE HERE
np.arange(5, 26, 3)

array([ 5,  8, 11, 14, 17, 20, 23])

7. Create an array of size 30 with evenly spaced values between -1 and 1.

In [13]:
# YOUR CODE HERE
np.linspace(-1,1,30)

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

8. Construct a 5x6 matrix with integers from 0 to 30.

In [14]:
# YOUR CODE HERE
np.arange(0, 30).reshape(5, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

9. Create an array of 30 random integers and sort it in ascending order.

In [23]:
# YOUR CODE HERE
np.sort(np.random.randint(0,1000,30))


array([ 27,  85, 159, 189, 224, 230, 242, 330, 339, 347, 376, 384, 472,
       505, 524, 555, 556, 573, 577, 619, 639, 645, 681, 698, 795, 795,
       797, 838, 952, 957])

10. Construct a 5x10 matrix filled with the value 1 at each location. Print the following details about this matrix:
- number of elements
- shape of the matrix
- the data type (using numpy methods)


In [26]:
# YOUR CODE HERE
array=np.ones((5,10))
print(array.size)
print(array.shape)
print(array.dtype)

50
(5, 10)
float64


11. Construct a 3x4x7 matrix with random integer values between 0 and 10 (a 3D matrix will be created).


In [28]:
# YOUR CODE HERE
np.random.randint(1, 10, size=(3, 4, 7))

array([[[9, 9, 2, 7, 3, 7, 9],
        [4, 1, 2, 1, 5, 5, 7],
        [9, 9, 3, 3, 3, 4, 8],
        [6, 8, 1, 8, 4, 1, 8]],

       [[4, 6, 8, 4, 3, 9, 3],
        [9, 2, 2, 2, 6, 3, 9],
        [4, 1, 4, 1, 5, 4, 8],
        [8, 7, 3, 1, 1, 3, 6]],

       [[7, 6, 6, 6, 3, 6, 8],
        [2, 5, 1, 1, 5, 3, 4],
        [3, 1, 1, 5, 6, 3, 9],
        [5, 8, 1, 5, 3, 1, 4]]])

12. Create an array of 20 random integers and reshape it into a 4x5 matrix.

In [31]:
# YOUR CODE HERE
np.random.randint(0,100,20).reshape(4,5)

array([[44, 19, 64,  7, 15],
       [13, 75, 86, 14, 91],
       [97, 65, 31, 86, 62],
       [85, 50, 24, 57, 62]])

13. Construct a one-dimensional array by concetanating 4 separate one-dimensional arrays.

In [33]:
# YOUR CODE HERE
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5])
array3 = np.array([6, 7, 8, 9])
array4 = np.array([10])

array = np.concatenate((array1, array2, array3, array4))
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

14. Create a vector of length 3 (3x1) and a matrix of size 3x3. Combine these two arrays on a
    column-by-column basis using numpy methods.


In [42]:
a = np.array([1, 2, 3]).reshape(-1, 1)
b = np.random.randint(0, 10, (3, 3))
c= np.concatenate((a,b),axis=  1)
c

array([[1, 4, 5, 8],
       [2, 4, 0, 3],
       [3, 4, 9, 9]])

In [40]:
np.argmax(b)

2

15. What is the difference between "axis=1" and "axis=0" in Numpy functions? 

YOUR ANSWER HERE
axis 1 is coulumn base concantration and axis 0 means row wise concantration

16. Create a random 1D vector with 20 elements. Find the 3rd, 5th and 7th elements of this vector.


In [46]:
# YOUR CODE HERE
a=np.arange(1,21,1)
print(a[2])
print(a[4])
print(a[6])

3
5
7


17. Create a random vector with 10 elements and replace the 4th element of this array with a different number.

In [51]:
# YOUR CODE HERE
a=np.random.randint(1,10,10)
print(a)
a[3]=88
a

[4 8 2 3 1 1 3 5 3 1]


array([ 4,  8,  2, 88,  1,  1,  3,  5,  3,  1])

18. Look up the concepts of *diagonal matrix* and *trace matrix* online and write a small explanation about what they are.


YOUR ANSWER HERE
A diagonal matrix is a square matrix with non-diagonal entries that are all zero and diagonal elements that are non-zero. The sum of a matrix's diagonal components yields a scalar number called the trace, which has features that are useful in different mathematical procedures.

19. Create a 5x5 diagonal matrix with elements of your choosing. What are the indexes of the diagonal?


In [55]:
# YOUR CODE HERE
np.diag([1,2,3,4,5])
#(1,1),(2,2),(3,3),(4,4),(5,5)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

20. Create a vector that ranges from 10 to 20. Print the values from the 3rd index to the last index.


In [56]:
# YOUR CODE HERE
a = np.arange(10, 21)  

print(a[2:]) 

[12 13 14 15 16 17 18 19 20]


21. Construct a 10x10 matrix with random elements and perform the following indexing tasks on it. Each task should be a single indexing operation.
 - Retrieve column 5 of row 3. Moreover;
 - Retrieve all elements of column 5.
 - Retrieve the 2nd row of all columns.
 - Retrieve row 2 through 7 of all columns.
 - Retrieve values with row index 2 to 5 and column index 3 to 7.
 - Retrieve the values from row index 5 to the end and column index from the top to 4.
 - Replace the value corresponding to the 5th row and the 5th column with your year of birth.

In [63]:
# YOUR CODE HERE
a=np.random.randint(1,100, size=(10,10))
print(a)
print(a[2,4])
print(a[:,4])
print(a[1,:])
print(a[1:7,:])
print(a[2:5,3:7])
print(a[5::,0:4])
a[5,5]=1988

[[ 7 51 72 42 64 15 29 33 94 27]
 [36 29 38 57 97 27 55 33 68 86]
 [66 10  5 74 97 38 13 31 47 88]
 [52 56 15 29  8  5 29 47 68 76]
 [45  2 27 95 36 36 26 43 27 69]
 [20 11 74 38  6 72 23 47 90 46]
 [12 90 13 62 82 89 97 60 43 76]
 [68  5 37 72 92 31  9 51 29 78]
 [40 41 86 11 23  1 46 21 90 36]
 [54 87 57  1 63 54 55 40 15 21]]
97
[64 97 97  8 36  6 82 92 23 63]
[36 29 38 57 97 27 55 33 68 86]
[[36 29 38 57 97 27 55 33 68 86]
 [66 10  5 74 97 38 13 31 47 88]
 [52 56 15 29  8  5 29 47 68 76]
 [45  2 27 95 36 36 26 43 27 69]
 [20 11 74 38  6 72 23 47 90 46]
 [12 90 13 62 82 89 97 60 43 76]]
[[74 97 38 13]
 [29  8  5 29]
 [95 36 36 26]]
[[20 11 74 38]
 [12 90 13 62]
 [68  5 37 72]
 [40 41 86 11]
 [54 87 57  1]]


22. Construct a one-dimensional array from 0 to 50 jumping with steps of 5 (`[5, 10, ...]`). Use the numpy methods to perform the following tasks;
- Print all values greater than 20.
- Print all values less than 30.
- How many values are 33 in it?
- Multiply all the elements of the created array by 5.

In [79]:
# YOUR CODE HERE
a=np.arange(5,50,5)
print(a[a>20])
print(a[a<30])
print(a[a==33].size)
b=a*5
b


[25 30 35 40 45]
[ 5 10 15 20 25]
0


array([ 25,  50,  75, 100, 125, 150, 175, 200, 225])

23. Construct an array of 50 random floats between 0 and 1 and take the average. Moreover;
- Get the standard deviation.
- Get the variance.
- Take the median.
- Find the smallest value.
- Find the largest value.

In [86]:
# YOUR CODE HERE
a=np.random.random(50)
print(np.average(a))
print(np.std(a))
print(np.var(a))
print(np.min(a))
print(np.max(a))

0.4417427005707003
0.2678672504744887
0.07175286387676248
0.0002375235758845795
0.9903413133417771


24. What are the differences between Pandas Series and NumPy arrays?

YOUR ANSWER HERE

25. Create a 5-element series with different data types, with an index of capital letters.

In [87]:
# YOUR CODE HERE
data = [10, 'Hello', 3.14, True, [1, 2, 3]]
index = ['A', 'B', 'C', 'D', 'E']

series = pd.Series(data, index=index)
print(series)

A           10
B        Hello
C         3.14
D         True
E    [1, 2, 3]
dtype: object


26. Create a 5-element dictionary with keys as country names and values as capitals and turn it into a series. An example: ` "france" : "paris"`).

In [89]:
# YOUR CODE HERE
dictionary = {
    'France': 'Paris',
    'Germany': 'Berlin',
    'Japan': 'Tokyo',
    'Brazil': 'Brasília',
    'Australia': 'Canberra'
}

series = pd.Series(dictionary)
series

France          Paris
Germany        Berlin
Japan           Tokyo
Brazil       Brasília
Australia    Canberra
dtype: object

27. Create a random vector with 10 elements.
- Convert the vector to series and with strings as indeces. For example, a,b,c,d,e,f,g..
- Retrieve the 3rd element of the series using the index name (for example: c).
- Retrieve the 1st element of the series using the index number.
- Access the 2nd and 7th elements of the series at the same time, using the index name. (Example: values corresponding to index b and g)

In [99]:
# YOUR CODE HERE
a=np.random.rand(10)
i = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
series = pd.Series(a, index=i)
print(series)
print(series['c'])
print(series[0])
print(series[['b','g']])



a    0.245286
b    0.157341
c    0.160400
d    0.334009
e    0.238690
f    0.930090
g    0.105834
h    0.698991
i    0.189222
j    0.881637
dtype: float64
0.1604001053300721
0.24528553225533456
b    0.157341
g    0.105834
dtype: float64


28. Create two 5-element series with elements of your choice with default index.
- Combine the series you have created.
- Arrange the index of the resulting concatenated 10-element series from 1 to 10.

In [100]:
# YOUR CODE HERE
series1 = pd.Series([10, 20, 30, 40, 50])  
series2 = pd.Series([60, 70, 80, 90, 100]) 

combined_series = pd.concat([series1, series2]) 

combined_series.index = range(1, 11) 

print(combined_series)

1      10
2      20
3      30
4      40
5      50
6      60
7      70
8      80
9      90
10    100
dtype: int64


**Bonus homework**:


Generate two 20x20 matrices with values between 0 and 1 randomly in a loop and take the difference of these
matrices. Repeat this process until all elements on the diagonal of the difference matrix
is between -0.1 and 0.1. When the desired matrix is found, let the program stop
and print the total number of cycles, how long it took, and the desired matrix
with print.


Tip: Finding the 20 x 20 matrix can take hours. Therefore, to test the accuracy
of your algorithm, you can first try it on small matrices such as 4x4, 5x5. And
you can try the latest 20x20 by increasing the number of matrix. (You can do
the matrix generation with the np.random.random((a,b)) function. It generates
an array of desired sizes between 0-1.)


In [8]:
# YOUR CODE HERE
import numpy as np
np.random.seed(42)
import time

size = 10

# record how long the while loop takes
start = time.time()

while True:
    # generate two random matrices of size 3x3
    a = np.random.random((size, size))
    b = np.random.random((size, size))

    diff = np.abs(a - b)
    # get diagonal of diff
    if np.all(np.diag(diff) <= 0.1):
        print("Found a match!")
        print("matrix 1:")
        print(a)
        print("matrix 2:")
        print(b)
        print("diagonal of diff:")
        print(np.diagonal(diff))
        break

# stop time
end = time.time()
print("Time taken: ", end - start)


[[0.80203982 0.30776679 0.96514057 0.22254882 0.96082357 0.88386248
  0.70451455 0.81831221 0.14548417 0.8959089 ]
 [0.98036683 0.14353201 0.28529909 0.69382485 0.60194746 0.475862
  0.31297111 0.97058358 0.17919567 0.15907398]
 [0.41137242 0.48203334 0.46616916 0.76720021 0.29136543 0.0795811
  0.78117109 0.12738464 0.68651872 0.39496577]
 [0.54496983 0.37466624 0.0617913  0.53042882 0.40448796 0.76969605
  0.20853571 0.51940513 0.91002657 0.00812047]
 [0.51407471 0.65924698 0.27077373 0.26043534 0.87028382 0.48404125
  0.11449501 0.35794764 0.08981719 0.08823397]
 [0.38782498 0.68402206 0.11227034 0.50878429 0.48766131 0.12199372
  0.95849971 0.98251215 0.55170378 0.59825786]
 [0.41522148 0.70202938 0.21248676 0.22896877 0.15433878 0.25010281
  0.46566852 0.06914628 0.39681494 0.55999141]
 [0.41197287 0.69454831 0.32287117 0.96678505 0.83378521 0.7331555
  0.70858667 0.12600876 0.34546425 0.00619238]
 [0.52984152 0.37588775 0.56028108 0.05727417 0.24793042 0.68294765
  0.52578849 0.6