## Data Manipulation module
### Homework assignment 1

Welcome to the first homework assignment of the data manipulation module. In this assignment you will be working with NumPy and Pandas Series. The goal of this assignment is to get you familiar with these libraries and data types.

### Instructions
Read the exercises carefully and implement the requested functionality. Add your code in the cells provided with `YOUR CODE HERE` or `YOUR ANSWER HERE`. You can add cells if you need to. **Make sure to use NumPy methods** to find your answers. In some cases you might be able to read the answer, but we want to see you using the NumPy methods.

### Hand-in
To hand in your assignment, fork this notebook and commit your changes, then make a pull request to the original repository. The deadline for handing in the assignment is **Wednesday 10-05 23:59**.

In [1]:
# imports, no need to edit

import numpy as np
import pandas as pd

np.random.seed(42)

1. Explain the difference between a vector and matrix in NumPy in one sentence.

A vector is a 1-dimensional array, but a matrix is a 2-dimensional array in NumPy

2. Construct a NumPy Array from a list of 10 elements.

In [3]:
# YOUR CODE HERE
lst = [2,7,0,3,4,2,4,5,8,10]
arr = np.array(lst)
arr

array([ 2,  7,  0,  3,  4,  2,  4,  5,  8, 10])

3. Construct a 10x10 matrix filled with '0's of the integer data type.

In [5]:
# YOUR CODE HERE
arr = np.zeros((10,10), dtype=int )
arr

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

4. Construct a 10x10 matrix filled with '1's, data type float.

In [6]:
# YOUR CODE HERE
arr = np.ones((10,10), dtype=float )
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

5. Construct a 10x10 matrix filled with '9's of the integer data type.

In [7]:
# YOUR CODE HERE
arr = np.full((10,10), 9, dtype=int)
arr

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

6. Construct a one-dimensional array with values between 5 and 25 that jumps with steps of 3 (`[5, 8, ...]`)

In [8]:
# YOUR CODE HERE
arr = np.arange(5,25,3)
arr

array([ 5,  8, 11, 14, 17, 20, 23])

7. Create an array of size 30 with evenly spaced values between -1 and 1.

In [13]:
# YOUR CODE HERE
arr = np.linspace(-1,1, num=30)
arr

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

8. Construct a 5x6 matrix with integers from 0 to 30.

In [16]:
# YOUR CODE HERE
arr = np.random.randint(30, size=(5,6) )
arr

array([[22, 20, 18, 15, 28, 18],
       [ 3, 28, 27, 17,  1,  0],
       [14,  4, 19, 10,  9,  1],
       [ 2, 22, 22, 11, 19,  4],
       [ 4,  5, 29,  8,  1, 20]])

9. Create an array of 30 random integers and sort it in ascending order.

In [18]:
# YOUR CODE HERE
arr = np.random.randint(100, size=30)
np.sort(arr)

array([ 3,  8, 13, 17, 21, 23, 24, 25, 28, 29, 36, 39, 41, 57, 58, 65, 69,
       72, 73, 74, 80, 80, 80, 84, 85, 86, 86, 95, 97, 98])

10. Construct a 5x10 matrix filled with the value 1 at each location. Print the following details about this matrix:
- number of elements
- shape of the matrix
- the data type (using numpy methods)


In [27]:
# YOUR CODE HERE
arr = np.ones((5,10))
print(arr)
print(f"The size of the matrix is: {arr.size}")
print(f"The shape of the matrix is: {arr.shape}")
print(f"The size of the type is: {arr.dtype}")

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
The size of the matrix is: 50
The shape of the matrix is: (5, 10)
The size of the type is: float64


11. Construct a 3x4x7 matrix with random integer values between 0 and 10 (a 3D matrix will be created).


In [28]:
# YOUR CODE HERE
arr = np.random.randint(10, size=(3,4,7) )
arr

array([[[3, 8, 5, 1, 0, 4, 8],
        [5, 9, 6, 4, 9, 5, 4],
        [8, 5, 7, 1, 8, 4, 6],
        [9, 0, 9, 4, 9, 1, 5]],

       [[0, 2, 4, 3, 2, 9, 4],
        [7, 3, 0, 6, 7, 2, 5],
        [1, 6, 7, 5, 5, 4, 7],
        [0, 9, 3, 3, 2, 2, 3]],

       [[0, 1, 8, 9, 1, 4, 8],
        [8, 7, 0, 0, 8, 7, 9],
        [8, 6, 2, 2, 1, 4, 2],
        [5, 1, 2, 4, 0, 0, 9]]])

12. Create an array of 20 random integers and reshape it into a 4x5 matrix.

In [31]:
# YOUR CODE HERE
arr = np.random.randint(100, size=20 )
print (arr)
print("the new matrix is :")
arr.reshape(4,5)

[71 58 86 92 81 94 93 38 98 17 58 16 13 30 23 98 59 44 97  2]
the new matrix is :


array([[71, 58, 86, 92, 81],
       [94, 93, 38, 98, 17],
       [58, 16, 13, 30, 23],
       [98, 59, 44, 97,  2]])

13. Construct a one-dimensional array by concetanating 4 separate one-dimensional arrays.

In [41]:
# YOUR CODE HERE
arry_1= np.random.randint(100, size=(5) )
arry_2= np.random.randint(100, size=(5) )
arry_3= np.random.randint(100, size=(5) )
arry_4= np.random.randint(100, size=(5) )
arr= np.concatenate([arry_1,arry_2,arry_3,arry_4])
print(f"array 1 is {arry_1}")
print(f"array 2 is {arry_2}")
print(f"array 3 is {arry_3}")
print(f"array 4 is {arry_4}")
print(f" all arrays in one: {arr}")

array 1 is [28  8 66 24 97]
array 2 is [75 41  8 78 39]
array 3 is [24  4 10 58 97]
array 4 is [87 78 37 71  4]
 all arrays in one: [28  8 66 24 97 75 41  8 78 39 24  4 10 58 97 87 78 37 71  4]


14. Create a vector of length 3 (3x1) and a matrix of size 3x3. Combine these two arrays on a
    column-by-column basis using numpy methods.


In [54]:
a = np.array([1, 2, 3]).reshape(-1, 1)
b = np.random.randint(0, 10, (3, 3))
print (f"First matrix :\n {a}")
print(f"Second matrix :\n {b}")
combined_arr = np.concatenate((a,b), axis=1)
print(f"combined matrix :\n {combined_arr}")
np.argmax(combined_arr)


First matrix :
 [[1]
 [2]
 [3]]
Second matrix :
 [[5 0 9]
 [5 0 5]
 [9 7 1]]
combined matrix :
 [[1 5 0 9]
 [2 5 0 5]
 [3 9 7 1]]


3

In [52]:
np.argmax(b)

7

15. What is the difference between "axis=1" and "axis=0" in Numpy functions? 

"axis =0" specifies that the operation should be performed along the rows.
"axis =1" specifies that the operation should be performed along the columns.


16. Create a random 1D vector with 20 elements. Find the 3rd, 5th and 7th elements of this vector.


In [55]:
# YOUR CODE HERE
arr = np.random.randint(100, size=20)
print(arr)
print(arr[2], arr[4],arr[6])

[49 13 63 46 28 75 35 98 51 75  6 28 10 32  5 78 31 50 74 57]
63 28 35


17. Create a random vector with 10 elements and replace the 4th element of this array with a different number.

In [56]:
# YOUR CODE HERE
arr = np.random.randint(100, size=10)
print(arr)
arr[3]=24
print (arr)

[86 25 97 45 97 28  3 80 98 12]
[86 25 97 24 97 28  3 80 98 12]


18. Look up the concepts of *diagonal matrix* and *trace matrix* online and write a small explanation about what they are.


A diagonal matrix is a special type of matrix where all the non-diagonal elements are zero.It has non-zero elements only on its main diagonal.
example: a 3x3 matrix,

2    0    0

0    1    0

0    0    8

A trace of a matrix is the sum of the elements on the main diagonal of the matrix. it is a useful quantity in the linear algebra.it is also equal to the sum of the eigenvalues of a matrix, which is another important concept in linear algebra.
example: the trace of the above matrix is : 2+1+8 = 11 


19. Create a 5x5 diagonal matrix with elements of your choosing. What are the indexes of the diagonal?


In [58]:
# YOUR CODE HERE
matrixs = np.diag([3,8,9,10,-3])
print (matrixs)
np.diag_indices_from(matrixs)

[[ 3  0  0  0  0]
 [ 0  8  0  0  0]
 [ 0  0  9  0  0]
 [ 0  0  0 10  0]
 [ 0  0  0  0 -3]]


(array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4]))

20. Create a vector that ranges from 10 to 20. Print the values from the 3rd index to the last index.


In [60]:
# YOUR CODE HERE
arr = np.arange(10,20)
arr[3:]

array([13, 14, 15, 16, 17, 18, 19])

21. Construct a 10x10 matrix with random elements and perform the following indexing tasks on it. Each task should be a single indexing operation.
 - Retrieve column 5 of row 3. Moreover;
 - Retrieve all elements of column 5.
 - Retrieve the 2nd row of all columns.
 - Retrieve row 2 through 7 of all columns.
 - Retrieve values with row index 2 to 5 and column index 3 to 7.
 - Retrieve the values from row index 5 to the end and column index from the top to 4.
 - Replace the value corresponding to the 5th row and the 5th column with your year of birth.

In [72]:
# YOUR CODE HERE
# note: the name for rows and columns is 1 to 10, but the indexes are 0 to 9
np.random.seed(42)
arr = np.random.randint(100, size=(10,10))
print(arr)
print("column 5 of row 3:\n",arr[2,4])
print("all elements of column 5:\n ",arr[:,4])
print("2nd row of all columns: \n",arr[1,:])
print("row 2 through 7 of all columns: \n",arr[1:7,:])
print("values with row index 2 to 5 and column index 3 to 7: \n", arr[2:5,3:7])
#assuming index 4 is inclusive.
print("values from row index 5 to end and column index from top to 4: \n", arr[5:,:5]) 
arr[4,4] = 87
print("replaced 5th row and 5th column with year of birth: \n", arr)


[[51 92 14 71 60 20 82 86 74 74]
 [87 99 23  2 21 52  1 87 29 37]
 [ 1 63 59 20 32 75 57 21 88 48]
 [90 58 41 91 59 79 14 61 61 46]
 [61 50 54 63  2 50  6 20 72 38]
 [17  3 88 59 13  8 89 52  1 83]
 [91 59 70 43  7 46 34 77 80 35]
 [49  3  1  5 53  3 53 92 62 17]
 [89 43 33 73 61 99 13 94 47 14]
 [71 77 86 61 39 84 79 81 52 23]]
column 5 of row 3:
 32
all elements of column 5:
  [60 21 32 59  2 13  7 53 61 39]
2nd row of all columns: 
 [87 99 23  2 21 52  1 87 29 37]
row 2 through 7 of all columns: 
 [[87 99 23  2 21 52  1 87 29 37]
 [ 1 63 59 20 32 75 57 21 88 48]
 [90 58 41 91 59 79 14 61 61 46]
 [61 50 54 63  2 50  6 20 72 38]
 [17  3 88 59 13  8 89 52  1 83]
 [91 59 70 43  7 46 34 77 80 35]]
values with row index 2 to 5 and column index 3 to 7: 
 [[20 32 75 57]
 [91 59 79 14]
 [63  2 50  6]]
values from row index 5 to end and column index from top to 4: 
 [[17  3 88 59 13]
 [91 59 70 43  7]
 [49  3  1  5 53]
 [89 43 33 73 61]
 [71 77 86 61 39]]
replaced 5th row and 5th column with 

22. Construct a one-dimensional array from 0 to 50 jumping with steps of 5 (`[5, 10, ...]`). Use the numpy methods to perform the following tasks;
- Print all values greater than 20.
- Print all values less than 30.
- How many values are 33 in it?
- Multiply all the elements of the created array by 5.

In [81]:
# YOUR CODE HERE
# assuming 50 is included
arr = np.arange(0,51,5)
print(arr)
index = arr > 20
print("all values greater than 20 \n",arr[index])
index = arr < 30
print("all values less than 30 \n",arr[index])
count = np.count_nonzero(arr == 33)
print (f"there are {count}  33's in the array")
print ("the whole array mul by 5: \n",np.multiply(arr,5))

[ 0  5 10 15 20 25 30 35 40 45 50]
all values greater than 20 
 [25 30 35 40 45 50]
all values less than 30 
 [ 0  5 10 15 20 25]
there are 0  33's in the array
the whole array mul by 5: 
 [  0  25  50  75 100 125 150 175 200 225 250]


23. Construct an array of 50 random floats between 0 and 1 and take the average. Moreover;
- Get the standard deviation.
- Get the variance.
- Take the median.
- Find the smallest value.
- Find the largest value.

In [84]:
# YOUR CODE HERE
np.random.seed(42)
arr = np.random.rand(50)
print(arr)
print("the Average of the array is:\n",np.average(arr))
print("the Standard deviation of the array is:\n",np.std(arr))
print("the Variance of the array is:\n",np.var(arr))
print("the Median of the array is:\n",np.median(arr))
print("the smallest value of the array is:\n",np.min(arr))
print("the largest of the array is:\n",np.max(arr))

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615 0.60111501 0.70807258 0.02058449 0.96990985
 0.83244264 0.21233911 0.18182497 0.18340451 0.30424224 0.52475643
 0.43194502 0.29122914 0.61185289 0.13949386 0.29214465 0.36636184
 0.45606998 0.78517596 0.19967378 0.51423444 0.59241457 0.04645041
 0.60754485 0.17052412 0.06505159 0.94888554 0.96563203 0.80839735
 0.30461377 0.09767211 0.68423303 0.44015249 0.12203823 0.49517691
 0.03438852 0.9093204  0.25877998 0.66252228 0.31171108 0.52006802
 0.54671028 0.18485446]
the Average of the array is:
 0.44592390439226115
the Standard deviation of the array is:
 0.2859797785370301
the Variance of the array is:
 0.08178443373208878
the Median of the array is:
 0.43604875619085853
the smallest value of the array is:
 0.020584494295802447
the largest of the array is:
 0.9699098521619943


24. What are the differences between Pandas Series and NumPy arrays?

- Indexing: NumPy arrays are indexed by integers, while Pandas Series can be indexed by either integers or labels.
- Data Types: NumPy arrays can only contain a single data type (e.g., all elements in the array must be integers or floats), while Pandas Series can contain a variety of data types (e.g., integers, floats, strings, etc.).
- Missing Data: NumPy arrays do not have built-in support for missing or null values, while Pandas Series do. Pandas Series can represent missing values using the special value 'NaN' (Not a Number), which can be helpful when working with real-world data that may have missing or incomplete information.
- Operations: NumPy arrays are optimized for mathematical operations, while Pandas Series are optimized for data manipulation and analysis. 

25. Create a 5-element series with different data types, with an index of capital letters.

In [85]:
# YOUR CODE HERE
a = [4,5.6,'hello',True,None]
sr = pd.Series(a,index=["I","F","S","B","N"])
sr

I        4
F      5.6
S    hello
B     True
N     None
dtype: object

26. Create a 5-element dictionary with keys as country names and values as capitals and turn it into a series. An example: ` "france" : "paris"`).

In [89]:
# YOUR CODE HERE
country_cap = {"Netherlands":"Amsterdam",
               "Belgium":"Brussels",
               "France":"Paris",
               "Norway":"Oslo",
               "Tigray":"Mekelle"}
sr=pd.Series(country_cap.keys(), index=country_cap.values())
print(sr)

Amsterdam    Netherlands
Brussels         Belgium
Paris             France
Oslo              Norway
Mekelle           Tigray
dtype: object


27. Create a random vector with 10 elements.
- Convert the vector to series and with strings as indeces. For example, a,b,c,d,e,f,g..
- Retrieve the 3rd element of the series using the index name (for example: c).
- Retrieve the 1st element of the series using the index number.
- Access the 2nd and 7th elements of the series at the same time, using the index name. (Example: values corresponding to index b and g)

In [100]:
# YOUR CODE HERE
np.random.seed(42)
arr = np.random.randint(100, size=10)
print(arr)
sr=pd.Series(arr, index=["a","b","c","d","e","f","g","h","i","j"])
print(sr)
print("the 3rd element of the series:\n",sr["c"])
print("the 1st element of the series:\n",sr[0])
print("access the 2nd and 7th element at the same time:\n",sr[["b","g"]])


[51 92 14 71 60 20 82 86 74 74]
a    51
b    92
c    14
d    71
e    60
f    20
g    82
h    86
i    74
j    74
dtype: int32
the 3rd element of the series:
 14
the 1st element of the series:
 51
access the 2nd and 7th element at the same time:
 b    92
g    82
dtype: int32


28. Create two 5-element series with elements of your choice with default index.
- Combine the series you have created.
- Arrange the index of the resulting concatenated 10-element series from 1 to 10.

In [111]:
# YOUR CODE HERE
a =[3,"hi",4,9,0]
b =[1,True,8,6,10]
sr1 = pd.Series(a, index =["A","B","C","D","E"])
sr2 = pd.Series(b, index =["F","G","H","I","J"])
sr = pd.concat([sr1,sr2])
print("combined series:\n", sr)
sr.index = range(1,11)
print("arranged index series:\n", sr)


combined series:
 A       3
B      hi
C       4
D       9
E       0
F       1
G    True
H       8
I       6
J      10
dtype: object
arranged index series:
 1        3
2       hi
3        4
4        9
5        0
6        1
7     True
8        8
9        6
10      10
dtype: object


**Bonus homework**:


Generate two 20x20 matrices with values between 0 and 1 randomly in a loop and take the difference of these
matrices. Repeat this process until all elements on the diagonal of the difference matrix
is between -0.1 and 0.1. When the desired matrix is found, let the program stop
and print the total number of cycles, how long it took, and the desired matrix
with print.


Tip: Finding the 20 x 20 matrix can take hours. Therefore, to test the accuracy
of your algorithm, you can first try it on small matrices such as 4x4, 5x5. And
you can try the latest 20x20 by increasing the number of matrix. (You can do
the matrix generation with the np.random.random((a,b)) function. It generates
an array of desired sizes between 0-1.)


In [122]:
# YOUR CODE HERE
import numpy as np
np.random.seed(42)
import time

size = 10

# record how long the while loop takes
start = time.time()
number_cycle = 0
while True:
    # generate two random matrices of size 3x3
    a = np.random.random((size, size))
    b = np.random.random((size, size))
    number_cycle+=1
    diff = np.abs(a - b)
    # get diagonal of diff
    if np.all(np.diag(diff) <= 0.1):
        print("Found a match!")
        print("matrix 1:")
        print(a)
        print("matrix 2:")
        print(b)
        print("diagonal of diff:")
        print(np.diagonal(diff))
        break

# stop time
end = time.time()
print(f"Time taken: {end - start} secs")
print("number of cycles: ", number_cycle)


Found a match!
matrix 1:
[[0.80203982 0.30776679 0.96514057 0.22254882 0.96082357 0.88386248
  0.70451455 0.81831221 0.14548417 0.8959089 ]
 [0.98036683 0.14353201 0.28529909 0.69382485 0.60194746 0.475862
  0.31297111 0.97058358 0.17919567 0.15907398]
 [0.41137242 0.48203334 0.46616916 0.76720021 0.29136543 0.0795811
  0.78117109 0.12738464 0.68651872 0.39496577]
 [0.54496983 0.37466624 0.0617913  0.53042882 0.40448796 0.76969605
  0.20853571 0.51940513 0.91002657 0.00812047]
 [0.51407471 0.65924698 0.27077373 0.26043534 0.87028382 0.48404125
  0.11449501 0.35794764 0.08981719 0.08823397]
 [0.38782498 0.68402206 0.11227034 0.50878429 0.48766131 0.12199372
  0.95849971 0.98251215 0.55170378 0.59825786]
 [0.41522148 0.70202938 0.21248676 0.22896877 0.15433878 0.25010281
  0.46566852 0.06914628 0.39681494 0.55999141]
 [0.41197287 0.69454831 0.32287117 0.96678505 0.83378521 0.7331555
  0.70858667 0.12600876 0.34546425 0.00619238]
 [0.52984152 0.37588775 0.56028108 0.05727417 0.24793042 0.