## Data Manipulation module
### Homework assignment 1

Welcome to the first homework assignment of the data manipulation module. In this assignment you will be working with NumPy and Pandas Series. The goal of this assignment is to get you familiar with these libraries and data types.

### Instructions
Read the exercises carefully and implement the requested functionality. Add your code in the cells provided with `YOUR CODE HERE` or `YOUR ANSWER HERE`. You can add cells if you need to. **Make sure to use NumPy methods** to find your answers. In some cases you might be able to read the answer, but we want to see you using the NumPy methods.

### Hand-in
To hand in your assignment, fork this notebook and commit your changes, then make a pull request to the original repository. The deadline for handing in the assignment is **Wednesday 10-05 23:59**.

In [2]:
# imports, no need to edit

import numpy as np
import pandas as pd

np.random.seed(42)

1. Explain the difference between a vector and matrix in NumPy in one sentence.

A vector is an array with only 1 dimension, and a matrix is 2 dimensional.

2. Construct a NumPy Array from a list of 10 elements.

In [16]:
array = np.random.randint(0, 10, size=10)
print(array)

[0 9 2 6 3 8 2 4 2 6]


3. Construct a 10x10 matrix filled with '0's of the integer data type.

In [22]:
matrix = np.zeros(shape=(10, 10), dtype='int32')
print(matrix)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


4. Construct a 10x10 matrix filled with '1's, data type float.

In [24]:
matrix = np.ones(shape=(10, 10), dtype='float')
print(matrix)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


5. Construct a 10x10 matrix filled with '9's of the integer data type.

In [28]:
matrix = np.full((10, 10), 9, dtype='int')
print(matrix)

[[9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]]


6. Construct a one-dimensional array with values between 5 and 25 that jumps with steps of 3 (`[5, 8, ...]`)

In [29]:
array = np.arange(5, 25, 3)
print(array)

[ 5  8 11 14 17 20 23]


7. Create an array of size 30 with evenly spaced values between -1 and 1.

In [34]:
array = np.linspace(-1, 1, 30)
print(array)

[-1.         -0.93103448 -0.86206897 -0.79310345 -0.72413793 -0.65517241
 -0.5862069  -0.51724138 -0.44827586 -0.37931034 -0.31034483 -0.24137931
 -0.17241379 -0.10344828 -0.03448276  0.03448276  0.10344828  0.17241379
  0.24137931  0.31034483  0.37931034  0.44827586  0.51724138  0.5862069
  0.65517241  0.72413793  0.79310345  0.86206897  0.93103448  1.        ]


8. Construct a 5x6 matrix with integers from 0 to 30.

In [37]:
matrix = np.arange(0, 30).reshape(5, 6)
print(matrix)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


9. Create an array of 30 random integers and sort it in ascending order.

In [44]:
array = np.random.randint(0, 100, size=30)
array.sort()
print(array)

[ 0  1 10 15 16 18 23 31 31 37 43 52 54 55 58 67 68 69 69 69 72 74 79 85
 86 89 95 96 96 97]


10. Construct a 5x10 matrix filled with the value 1 at each location. Print the following details about this matrix:
- number of elements
- shape of the matrix
- the data type (using numpy methods)


In [56]:
matrix = np.ones(shape=(5,10), dtype='int')
print(matrix)
print()
print("Matrix size: ", matrix.size)
print()
print("Matrix shape: ", matrix.shape)
print()
print("Matrix data type: ", matrix.dtype)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]

Matrix size:  50

Matrix shape:  (5, 10)

Matrix data type:  int32


11. Construct a 3x4x7 matrix with random integer values between 0 and 10 (a 3D matrix will be created).


In [72]:
matrix = np.random.randint(0, 100, (3, 4, 7))
print(matrix)

[[[85 83 12 19 65 98 46]
  [18 44 36 53  5 13  3]
  [85 54 99 33 26  6  2]
  [46 96  1 79 24 59 78]]

 [[23 14 94 13 53 77  5]
  [77 80 17 19 61 80 79]
  [39 38 51 31 72 26 51]
  [96 62 73 62 16 48 99]]

 [[80 81 22 97 71 12 22]
  [56 61 53 19 85 51 22]
  [34 66 33 32 45 80 44]
  [18 93 86 14 77 65 38]]]


12. Create an array of 20 random integers and reshape it into a 4x5 matrix.

In [62]:
matrix = np.random.randint(0, 100, size=20).reshape(4, 5)
print(matrix)

[[ 7 15 13 75 86]
 [14 91 97 65 31]
 [86 62 85 50 24]
 [57 62 61 21 57]]


13. Construct a one-dimensional array by concetanating 4 separate one-dimensional arrays.

In [70]:
array1 = np.random.randint(0, 10, size=5)
array2 = np.random.randint(0, 10, size=5)
array3 = np.random.randint(0, 10, size=5)
array4 = np.random.randint(0, 10, size=5)
res_array = np.concatenate([array1, array2, array3, array4])
print(res_array)

[6 8 2 8 0 0 3 8 5 2 0 3 8 2 8 6 3 2 9 4]


14. Create a vector of length 3 (3x1) and a matrix of size 3x3. Combine these two arrays on a
    column-by-column basis using numpy methods.


In [83]:
matrix1 = np.array([1, 2, 3]).reshape(-1, 1)
matrix2 = np.random.randint(0, 10, (3, 3))
print(matrix1)
print()
print(matrix2)
print()
c = np.concatenate([matrix2, matrix1], axis=1)
print(c)

[[1]
 [2]
 [3]]

[[5 3 7]
 [7 4 5]
 [2 0 8]]

[[5 3 7 1]
 [7 4 5 2]
 [2 0 8 3]]


In [90]:
np.argmax(matrix2)


8

15. What is the difference between "axis=1" and "axis=0" in Numpy functions? 

"axis=0" means that the operation is preformed acroos the rows, and "axis=1" means the operation is performed accross the columns.

16. Create a random 1D vector with 20 elements. Find the 3rd, 5th and 7th elements of this vector.


In [93]:
array = np.random.randint(0, 10, size=20)
print(array)
print()
print(array[[2, 4, 6]])

[3 8 8 1 4 0 3 1 7 3 4 3 4 4 4 2 6 2 1 2]

[8 4 3]


17. Create a random vector with 10 elements and replace the 4th element of this array with a different number.

In [95]:
array = np.random.randint(0, 10, size=10)
print(array)
print()
array[3] = 99
print(array)

[7 4 3 6 0 5 7 6 1 6]

[ 7  4  3 99  0  5  7  6  1  6]


18. Look up the concepts of *diagonal matrix* and *trace matrix* online and write a small explanation about what they are.


A diagonal matrix is a square matrix where all the elements outside the main diagonal have the value of 0.

The trace of a square matrix is the sum of its diagonal values.

19. Create a 5x5 diagonal matrix with elements of your choosing. What are the indexes of the diagonal?


In [103]:
matrix = np.diag([1, 2, 3, 4, 5, 6])
print(matrix)
print()
diag_ind = np.diag_indices_from(matrix)
print(diag_ind)
print()
print(list(zip(*diag_ind)))


[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]

(array([0, 1, 2, 3, 4, 5]), array([0, 1, 2, 3, 4, 5]))

[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]


20. Create a vector that ranges from 10 to 20. Print the values from the 3rd index to the last index.


In [33]:
vector = np.arange(10, 20)
print(vector[2:])

[12 13 14 15 16 17 18 19]


21. Construct a 10x10 matrix with random elements and perform the following indexing tasks on it. Each task should be a single indexing operation.
 - Retrieve column 5 of row 3. Moreover;
 - Retrieve all elements of column 5.
 - Retrieve the 2nd row of all columns.
 - Retrieve row 2 through 7 of all columns.
 - Retrieve values with row index 2 to 5 and column index 3 to 7.
 - Retrieve the values from row index 5 to the end and column index from the top to 4.
 - Replace the value corresponding to the 5th row and the 5th column with your year of birth.

In [44]:
matrix = np.random.randint(0, 100, (10, 10))
print(matrix)
print()
print(matrix[3, 5])
print()
print(matrix[:, 5])
print()
print(matrix[1,:])
print()
print(matrix[2:8, :])
print()
print(matrix[2:6, 3:8])
print()
print(matrix[5:, 0:5])
print()
matrix[4,4] = 1991
print(matrix)

[[33  7 39 82 41 40  5 51 25 63]
 [97 58 55 58 69 32 52 21 20 69]
 [69  3 93 74 61 61 93 94 23 54]
 [ 8  2 30 39 35 23 94  5 65 83]
 [91 74  3 78  5 93 50 61 56 65]
 [78 74  7 25 50 44 43  4 69 25]
 [67 18 83 96 19 11 46  0 89 13]
 [63 37 36 10 99 76  2 32  5 49]
 [ 9  4 22  9 43  1 12 39  1 83]
 [64 62 72 16  8 74 14 23 37 34]]

23

[40 32 61 23 93 44 11 76  1 74]

[97 58 55 58 69 32 52 21 20 69]

[[69  3 93 74 61 61 93 94 23 54]
 [ 8  2 30 39 35 23 94  5 65 83]
 [91 74  3 78  5 93 50 61 56 65]
 [78 74  7 25 50 44 43  4 69 25]
 [67 18 83 96 19 11 46  0 89 13]
 [63 37 36 10 99 76  2 32  5 49]]

[[74 61 61 93 94]
 [39 35 23 94  5]
 [78  5 93 50 61]
 [25 50 44 43  4]]

[[78 74  7 25 50]
 [67 18 83 96 19]
 [63 37 36 10 99]
 [ 9  4 22  9 43]
 [64 62 72 16  8]]

[[  33    7   39   82   41   40    5   51   25   63]
 [  97   58   55   58   69   32   52   21   20   69]
 [  69    3   93   74   61   61   93   94   23   54]
 [   8    2   30   39   35   23   94    5   65   83]
 [  91   74    3   7

22. Construct a one-dimensional array from 0 to 50 jumping with steps of 5 (`[5, 10, ...]`). Use the numpy methods to perform the following tasks;
- Print all values greater than 20.
- Print all values less than 30.
- How many values are 33 in it?
- Multiply all the elements of the created array by 5.

In [50]:
array = np.arange(0, 50, 5)
print(array)
print()
print(array[array > 20])
print()
print(array[array < 30])
print()
print(array[array == 33].size)
print()
print(array * 5)

[ 0  5 10 15 20 25 30 35 40 45]

[25 30 35 40 45]

[ 0  5 10 15 20 25]

0

[  0  25  50  75 100 125 150 175 200 225]


23. Construct an array of 50 random floats between 0 and 1 and take the average. Moreover;
- Get the standard deviation.
- Get the variance.
- Take the median.
- Find the smallest value.
- Find the largest value.

In [63]:
array = np.random.rand(50)
print(array)
print()
print("Average: ", array.mean())
print("Standard deviation: ", array.std())
print("Median: ", np.median(array))
print("Smallest value: ", array.min())
print("Largest value: ", array.max())

[0.45231828 0.6435777  0.52640266 0.73158952 0.08162998 0.06035208
 0.24710323 0.15954468 0.87178357 0.21921399 0.97586526 0.33689579
 0.18211792 0.78969851 0.65870778 0.49819572 0.55536355 0.71920178
 0.22845474 0.99633392 0.97479316 0.65032569 0.19954245 0.68022824
 0.07219841 0.0306525  0.25768289 0.46262296 0.86827251 0.72716907
 0.74270652 0.42549333 0.34593499 0.37103876 0.98764956 0.04010919
 0.8670315  0.57867541 0.43861542 0.72525766 0.48666894 0.87342324
 0.90070186 0.42172093 0.2768278  0.59235033 0.91236335 0.21066219
 0.62296658 0.63156022]

Average:  0.5261919260812862
Standard deviation:  0.28511014669533263
Median:  0.5408831059368722
Smallest value:  0.030652502205806065
Largest value:  0.9963339160567419


24. What are the differences between Pandas Series and NumPy arrays?

Numpy arrays have a fixed size, fixed datatype, and they are focused on numerical operations.

Pandas series can hold different datatypes, can change dimensions, have named/labeled indecis.

25. Create a 5-element series with different data types, with an index of capital letters.

In [64]:
series = pd.Series([False, 1, 2.0, "3", [4]], index=['A', 'B', 'C', 'D', 'E'])
print(series)

A    False
B        1
C      2.0
D        3
E      [4]
dtype: object


26. Create a 5-element dictionary with keys as country names and values as capitals and turn it into a series. An example: ` "france" : "paris"`).

In [65]:
d = {
    'Netherlands': 'Amsterdam',
    'France': 'Paris',
    'Germany': 'Berlin',
    'Spain': 'Madrid',
    'UK': 'London'
}
series = pd.Series(d)
print(series)

Netherlands    Amsterdam
France             Paris
Germany           Berlin
Spain             Madrid
UK                London
dtype: object


27. Create a random vector with 10 elements.
- Convert the vector to series and with strings as indeces. For example, a,b,c,d,e,f,g..
- Retrieve the 3rd element of the series using the index name (for example: c).
- Retrieve the 1st element of the series using the index number.
- Access the 2nd and 7th elements of the series at the same time, using the index name. (Example: values corresponding to index b and g)

In [69]:
vector = np.random.randint(0, 10, size=10)
print(vector)
print()
series = pd.Series(vector, index=['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'])
print(series)
print()
print(series[0])
print()
print(series[['B', 'G']])

[7 3 6 9 2 5 9 9 8 0]

A    7
B    3
C    6
D    9
E    2
F    5
G    9
H    9
I    8
J    0
dtype: int32

7

B    3
G    9
dtype: int32


28. Create two 5-element series with elements of your choice with default index.
- Combine the series you have created.
- Arrange the index of the resulting concatenated 10-element series from 1 to 10.

In [72]:
series1 = pd.Series([10, 20, 30, 40, 50])
series2 = pd.Series([60, 70, 80, 90, 100])
res_series = pd.concat([series1, series2])
print(res_series)
print()
res_series.index = range(1, 11)
print(res_series)

0     10
1     20
2     30
3     40
4     50
0     60
1     70
2     80
3     90
4    100
dtype: int64

1      10
2      20
3      30
4      40
5      50
6      60
7      70
8      80
9      90
10    100
dtype: int64


**Bonus homework**:


Generate two 20x20 matrices with values between 0 and 1 randomly in a loop and take the difference of these
matrices. Repeat this process until all elements on the diagonal of the difference matrix
is between -0.1 and 0.1. When the desired matrix is found, let the program stop
and print the total number of cycles, how long it took, and the desired matrix
with print.


Tip: Finding the 20 x 20 matrix can take hours. Therefore, to test the accuracy
of your algorithm, you can first try it on small matrices such as 4x4, 5x5. And
you can try the latest 20x20 by increasing the number of matrix. (You can do
the matrix generation with the np.random.random((a,b)) function. It generates
an array of desired sizes between 0-1.)


In [32]:
import time
import numpy as np

np.random.seed(42)

# the shape of the matrix, (5, 5) for faster testing
shape = (10, 10)

start_t = time.time()

iterations = 0

while True:
    iterations += 1
    
    matrix1 = np.random.uniform(0,1,shape)
    matrix2 = np.random.uniform(0,1,shape)
    diff = np.absolute(matrix1 - matrix2)
    
    diag = np.diagonal(diff)
    if np.all(diag <= 0.1):
        print("FOUND!")
        break

end_t = time.time()
total_t = time.strftime("%H:%M:%S.%m", time.gmtime(end_t - start_t))

print('Number of iterations: ', iterations)
print('Time to find the result: ', total_t)
print('The desired matrix: ')
print(diff)


FOUND!
Number of iterations:  312021
Time to find the result:  00:00:05.01
The desired matrix: 
[[8.03126822e-02 1.73440505e-02 3.22440336e-01 1.65907265e-01
  6.47902672e-01 2.29088736e-01 1.26382781e-02 5.40575805e-01
  9.77875266e-02 3.60467467e-01]
 [5.56235930e-01 7.59914601e-02 2.77292879e-01 1.95061719e-01
  2.33622796e-02 2.51494378e-01 2.98453525e-01 3.03852351e-01
  1.60469570e-01 3.58741278e-02]
 [1.41430637e-01 4.10521627e-01 6.43315639e-03 4.93778250e-01
  2.57457735e-01 8.89553261e-01 1.50780382e-01 2.43214901e-01
  3.86926414e-01 1.99039192e-01]
 [3.72931356e-01 2.67318896e-01 2.39286885e-02 6.14089348e-02
  1.70044576e-01 3.55815131e-01 8.45704920e-02 8.99426185e-02
  8.22582813e-01 3.81904941e-01]
 [2.97665375e-04 1.25352349e-01 1.35564791e-01 4.60193987e-01
  1.04129767e-02 2.85930449e-01 4.70912925e-01 4.91651968e-01
  3.56135470e-03 5.53607541e-01]
 [1.00580557e-02 1.61632660e-02 7.24999219e-02 1.97565138e-01
  3.93395816e-02 5.51391761e-02 5.82848931e-01 6.02714810