## Data Manipulation module
### Homework assignment 1

Welcome to the first homework assignment of the data manipulation module. In this assignment you will be working with NumPy and Pandas Series. The goal of this assignment is to get you familiar with these libraries and data types.

### Instructions
Read the exercises carefully and implement the requested functionality. Add your code in the cells provided with `YOUR CODE HERE` or `YOUR ANSWER HERE`. You can add cells if you need to. **Make sure to use NumPy methods** to find your answers. In some cases you might be able to read the answer, but we want to see you using the NumPy methods.

### Hand-in
To hand in your assignment, fork this notebook and commit your changes, then make a pull request to the original repository. The deadline for handing in the assignment is **Wednesday 10-05 23:59**.

In [3]:
# imports, no need to edit

import numpy as np
import pandas as pd

np.random.seed(42)

1. Explain the difference between a vector and matrix in NumPy in one sentence.

 vector is an array (or list) with one dimension and a matrix is a vector with two dimensions or more.

2. Construct a NumPy Array from a list of 10 elements.

In [6]:
array = np.random.rand(10)


print(array)


[0.95071431 0.73199394 0.59865848 0.15601864 0.15599452 0.05808361
 0.86617615 0.60111501 0.70807258 0.02058449]


3. Construct a 10x10 matrix filled with '0's of the integer data type.

In [10]:
matrix = np.zeros( (10, 10), dtype=int)

print (matrix)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


4. Construct a 10x10 matrix filled with '1's, data type float.

In [13]:
matrix = np.ones((10, 10))

print (matrix)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


5. Construct a 10x10 matrix filled with '9's of the integer data type.

In [15]:
matrix = np.full( (10, 10), 9, dtype=int)

print (matrix)

[[9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9]]


6. Construct a one-dimensional array with values between 5 and 25 that jumps with steps of 3 (`[5, 8, ...]`)

In [17]:
array = np.arange(5, 25, 3)

print (array)


[ 5  8 11 14 17 20 23]


7. Create an array of size 30 with evenly spaced values between -1 and 1.

In [19]:
# YOUR CODE HERE




[-1.         -0.93103448 -0.86206897 -0.79310345 -0.72413793 -0.65517241
 -0.5862069  -0.51724138 -0.44827586 -0.37931034 -0.31034483 -0.24137931
 -0.17241379 -0.10344828 -0.03448276  0.03448276  0.10344828  0.17241379
  0.24137931  0.31034483  0.37931034  0.44827586  0.51724138  0.5862069
  0.65517241  0.72413793  0.79310345  0.86206897  0.93103448  1.        ]


8. Construct a 5x6 matrix with integers from 0 to 30.

In [24]:
matrix = np.arange(0, 30)
print (matrix)
print ()

final_matrix = matrix.reshape(5, 6)
print (final_matrix)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


9. Create an array of 30 random integers and sort it in ascending order.

In [27]:
array = np.random.randint(0, 100, 30)
print (array)
print ()

sortedArray = np.sort(array)

print(sortedArray)


[53 92 62 17 89 43 33 73 61 99 13 94 47 14 71 77 86 61 39 84 79 81 52 23
 25 88 59 40 28 14]

[13 14 14 17 23 25 28 33 39 40 43 47 52 53 59 61 61 62 71 73 77 79 81 84
 86 88 89 92 94 99]


10. Construct a 5x10 matrix filled with the value 1 at each location. Print the following details about this matrix:
- number of elements
- shape of the matrix
- the data type (using numpy methods)


In [28]:

matrix = np.ones((5, 10))

print (matrix)

print ()

print (matrix.size)

print ()

print (matrix.shape)

print ()

print (matrix.dtype)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

50

(5, 10)

float64


11. Construct a 3x4x7 matrix with random integer values between 0 and 10 (a 3D matrix will be created).


In [30]:
matrix = np.random.randint(0, 10, size=(3, 4, 7))

print (matrix)

[[[8 4 0 2 9 7 5]
  [7 8 3 0 0 9 3]
  [6 1 2 0 4 0 7]
  [0 0 1 1 5 6 4]]

 [[0 0 2 1 4 9 5]
  [6 3 6 7 0 5 7]
  [4 3 1 5 5 0 8]
  [5 2 3 3 2 9 2]]

 [[2 3 6 3 8 0 7]
  [6 1 7 0 8 8 1]
  [6 9 2 6 9 8 3]
  [0 1 0 4 4 6 8]]]


12. Create an array of 20 random integers and reshape it into a 4x5 matrix.

In [31]:
array = np.random.randint(0, 100, size=20)

print (array)

print ()

reshaped = array.reshape((4, 5))

print (reshaped)

[98 18 47 79  2 19 23 53 32 23 74 71 35 37 83 98 88 98 24 92]

[[98 18 47 79  2]
 [19 23 53 32 23]
 [74 71 35 37 83]
 [98 88 98 24 92]]


13. Construct a one-dimensional array by concetanating 4 separate one-dimensional arrays.

In [40]:

# Not sure if the size is correct????????????

array1 = np.random.randint(0, 100, size=2)
array2 = np.random.randint(0, 100, size=2)
array3 = np.random.randint(0, 100, size=2)
array4 = np.random.randint(0, 100, size=2)

print (array1, array2, array3, array4)
print ()

concatArray = np.concatenate((array1, array2, array3, array4))

print (concatArray)


[52 94] [98 59] [96 62] [84 31]

[52 94 98 59 96 62 84 31]


14. Create a vector of length 3 (3x1) and a matrix of size 3x3. Combine these two arrays on a
    column-by-column basis using numpy methods.


In [41]:
a = np.array([1, 2, 3]).reshape(-1, 1)
b = np.random.randint(0, 10, (3, 3))

In [44]:
np.argmax(b)

5

15. What is the difference between "axis=1" and "axis=0" in Numpy functions? 

axis=1 is for rows and axis=0 is for columns.

16. Create a random 1D vector with 20 elements. Find the 3rd, 5th and 7th elements of this vector.


In [47]:
vector = np.random.rand(20)

print (vector)
print ()
print (vector[2]) #3rd element
print (vector[4]) #5th element
print (vector[6]) #7th element

[0.62289048 0.08534746 0.05168172 0.53135463 0.54063512 0.6374299
 0.72609133 0.97585208 0.51630035 0.32295647 0.79518619 0.27083225
 0.43897142 0.07845638 0.02535074 0.96264841 0.83598012 0.69597421
 0.40895294 0.17329432]

0.0516817211686077
0.5406351216101065
0.7260913337226615


17. Create a random vector with 10 elements and replace the 4th element of this array with a different number.

In [50]:
vector = np.random.rand(10)

print (vector)
vector[3] = 77

print ()
print (vector)


[0.47417383 0.09783416 0.49161588 0.47347177 0.17320187 0.43385165
 0.39850473 0.6158501  0.63509365 0.04530401]

[4.74173829e-01 9.78341607e-02 4.91615875e-01 7.70000000e+01
 1.73201870e-01 4.33851649e-01 3.98504734e-01 6.15850098e-01
 6.35093651e-01 4.53040098e-02]


18. Look up the concepts of *diagonal matrix* and *trace matrix* online and write a small explanation about what they are.


diagonal matrix is a square matrix where all elements (outside the main diagonal) are zero, and the trace of a matrix is the sum of its diagonal elements.


19. Create a 5x5 diagonal matrix with elements of your choosing. What are the indexes of the diagonal?


In [57]:
elements = np.random.randint(0, 10, size=5)

print (elements)

diagonal_matrix = np.diag(elements)

print ()
print (diagonal_matrix)

[0 9 7 9 9]

[[0 0 0 0 0]
 [0 9 0 0 0]
 [0 0 7 0 0]
 [0 0 0 9 0]
 [0 0 0 0 9]]


20. Create a vector that ranges from 10 to 20. Print the values from the 3rd index to the last index.


In [59]:
vector = np.arange(10, 20)

print (vector)
print ()

print(vector[2:])

[10 11 12 13 14 15 16 17 18 19]

[12 13 14 15 16 17 18 19]


21. Construct a 10x10 matrix with random elements and perform the following indexing tasks on it. Each task should be a single indexing operation.
 - Retrieve column 5 of row 3. Moreover;
 - Retrieve all elements of column 5.
 - Retrieve the 2nd row of all columns.
 - Retrieve row 2 through 7 of all columns.
 - Retrieve values with row index 2 to 5 and column index 3 to 7.
 - Retrieve the values from row index 5 to the end and column index from the top to 4.
 - Replace the value corresponding to the 5th row and the 5th column with your year of birth.

In [70]:

# Create a 10x10 matrix with random elements
matrix = np.random.rand(10, 10)

print (matrix)
print ()

# Retrieve column 5 of row 3
one = matrix[2, 4]

print (one)
print ()


# Retrieve all elements of column 5
two = matrix[:, 4]
print (two)
print ()

# Retrieve the 2nd row of all columns
three = matrix[1, :]
print (three)
print ()

# Retrieve row 2 through 7 of all columns
four = matrix[1:7, :]

print (four)
print ()


# Retrieve values with row index 2 to 5 and column index 3 to 7
five = matrix[1:5, 2:7]

print (five)
print ()


# Retrieve the values from row index 5 to the end and column index from the top to 4
six = matrix[4:, :4]

print (six)
print ()

# Replace the value corresponding to the 5th row and the 5th column with your year of birth
matrix[4, 4] = 1994
print (matrix)
print ()


[[0.51481735 0.35923337 0.59295085 0.16352387 0.39108154 0.96941232
  0.25813343 0.65673666 0.32519006 0.77347313]
 [0.13087366 0.96982105 0.45378954 0.23605046 0.07349675 0.16975791
  0.51977395 0.33700318 0.82888337 0.43088752]
 [0.24871427 0.61714499 0.70677722 0.16704191 0.16761922 0.03667143
  0.73640202 0.66380453 0.47463088 0.84417045]
 [0.80567015 0.58535436 0.86827128 0.20584121 0.11191962 0.26974961
  0.05708686 0.53116953 0.93660569 0.03934354]
 [0.12210991 0.45219903 0.93387502 0.3161561  0.50723481 0.04157286
  0.1483432  0.98663012 0.9651187  0.00493998]
 [0.95181179 0.63911994 0.86791829 0.45473986 0.51559603 0.48884658
  0.66686426 0.13965125 0.02997359 0.30792994]
 [0.70468076 0.20185345 0.67343243 0.96991205 0.09390072 0.67260212
  0.44375022 0.86814225 0.17714979 0.69262595]
 [0.83811529 0.94461422 0.68324803 0.49717476 0.61784724 0.86890498
  0.57060975 0.03038706 0.9309487  0.68952675]
 [0.67651339 0.21567515 0.65888547 0.39386441 0.65123298 0.10659303
  0.6578453 

22. Construct a one-dimensional array from 0 to 50 jumping with steps of 5 (`[5, 10, ...]`). Use the numpy methods to perform the following tasks;
- Print all values greater than 20.
- Print all values less than 30.
- How many values are 33 in it?
- Multiply all the elements of the created array by 5.

In [71]:
array = np.arange(0, 50, 5)

print (array)
print ()

# Print all values greater than 20
greater_than_20 = array[array > 20]

print (greater_than_20)
print ()


# Print all values less than 30
less_than_30 = array[array < 30]
print (less_than_30)
print ()


# Count the number of values that are 33
count_33 = np.count_nonzero(array == 33)
print (count_33)
print ()

# Multiply all elements of the array by 5
multiply = array * 5

print (multiply)




[ 0  5 10 15 20 25 30 35 40 45]

[25 30 35 40 45]

[ 0  5 10 15 20 25]

0

[  0  25  50  75 100 125 150 175 200 225]


23. Construct an array of 50 random floats between 0 and 1 and take the average. Moreover;
- Get the standard deviation.
- Get the variance.
- Take the median.
- Find the smallest value.
- Find the largest value.

In [72]:

# Construct an array of 50 random floats between 0 and 1
array = np.random.rand(50)
print (array)
print ()

# Calculate the average
average = np.average(array)
print (average)
print ()

# Calculate the standard deviation
std_deviation = np.std(array)
print (std_deviation)
print ()

# Calculate the variance
variance = np.var(array)
print (variance)
print ()

# Calculate the median
median = np.median(array)
print (median)
print ()

# Find the smallest value
smallest_value = np.min(array)
print (smallest_value)
print ()

# Find the largest value
largest_value = np.max(array)
print (largest_value)


[0.76228513 0.79781365 0.43558331 0.81783422 0.12020906 0.5444891
 0.00575866 0.32458583 0.36646153 0.39617269 0.69546721 0.3885581
 0.44869362 0.23754413 0.37325179 0.22726963 0.07319592 0.60344859
 0.6682128  0.61949035 0.46349404 0.37978578 0.86333365 0.51908179
 0.47918188 0.02564207 0.34124783 0.38019562 0.39882278 0.58017237
 0.53360255 0.60790509 0.76488326 0.81298574 0.71812308 0.9555237
 0.01823258 0.19577799 0.00756287 0.64747471 0.89803055 0.2434823
 0.92703454 0.06026739 0.93443603 0.35162269 0.10142083 0.48587176
 0.25677657 0.2848729 ]

0.46286340493971756

0.26912841286644046

0.07243010261200923

0.4421384687177318

0.0057586604981215705

0.9555236959549347


24. What are the differences between Pandas Series and NumPy arrays?

Numpy can only be used for elements that are numbers while Pandas can have elements of different data types.

25. Create a 5-element series with different data types, with an index of capital letters.

In [76]:

indexs_to_use = ['A', 'B', 'C', 'D', 'E']


data_to_use = [10, "Hello", 3.14, True, [1, 2, 3]]


panda_elements = pd.Series(data=data_to_use, index=indexs_to_use)

print(panda_elements)

A           10
B        Hello
C         3.14
D         True
E    [1, 2, 3]
dtype: object


26. Create a 5-element dictionary with keys as country names and values as capitals and turn it into a series. An example: ` "france" : "paris"`).

In [77]:

capitals = {'The Netherlands': 'Amsterdam',
             'Belgium': 'Brussels',
               'Germany': 'Berlin',
               'Jordan': 'Amman',
                 'Turkey': 'Ankara'}


panda = pd.Series(capitals)

print(panda)

The Netherlands    Amsterdam
Belgium             Brussels
Germany               Berlin
Jordan                 Amman
Turkey                Ankara
dtype: object


27. Create a random vector with 10 elements.
- Convert the vector to series and with strings as indeces. For example, a,b,c,d,e,f,g..
- Retrieve the 3rd element of the series using the index name (for example: c).
- Retrieve the 1st element of the series using the index number.
- Access the 2nd and 7th elements of the series at the same time, using the index name. (Example: values corresponding to index b and g)

In [78]:

# Create a random vector with 10 elements
vector = np.random.rand(10)

print (vector)
print ()

# Convert the vector to a Pandas Series with string indices
to_panda = pd.Series(vector, index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])

print (to_panda)
print ()

# Retrieve the 3rd element of the series using the index name
print(to_panda['c'])
print ()

# Retrieve the 1st element of the series using the index number
print(to_panda[0])
print ()

# Access the 2nd and 7th elements of the series at the same time, using the index name
print(to_panda[['b', 'g']])


[0.30728996 0.8030259  0.53916128 0.3113077  0.61033378 0.71615067
 0.272624   0.4135491  0.12188609 0.18114935]

a    0.307290
b    0.803026
c    0.539161
d    0.311308
e    0.610334
f    0.716151
g    0.272624
h    0.413549
i    0.121886
j    0.181149
dtype: float64

0.5391612766752545

0.3072899649262866

b    0.803026
g    0.272624
dtype: float64


28. Create two 5-element series with elements of your choice with default index.
- Combine the series you have created.
- Arrange the index of the resulting concatenated 10-element series from 1 to 10.

In [5]:

# Create two series with elements of your choice
series1 = pd.Series([10, 20, 30, 40, 50])
print (series1)
print ()

series2 = pd.Series(['A', 'B', 'C', 'D', 'E'])
print (series2)
print ()

# Combine the series
combined = pd.concat([series1, series2])
print (combined)
print ()

# Arrange the index of the resulting concatenated series from 1 to 10
combined.index = range(1, 11)

print(combined)

0    10
1    20
2    30
3    40
4    50
dtype: int64

0    A
1    B
2    C
3    D
4    E
dtype: object

0    10
1    20
2    30
3    40
4    50
0     A
1     B
2     C
3     D
4     E
dtype: object

1     10
2     20
3     30
4     40
5     50
6      A
7      B
8      C
9      D
10     E
dtype: object


**Bonus homework**:


Generate two 20x20 matrices with values between 0 and 1 randomly in a loop and take the difference of these
matrices. Repeat this process until all elements on the diagonal of the difference matrix
is between -0.1 and 0.1. When the desired matrix is found, let the program stop
and print the total number of cycles, how long it took, and the desired matrix
with print.


Tip: Finding the 20 x 20 matrix can take hours. Therefore, to test the accuracy
of your algorithm, you can first try it on small matrices such as 4x4, 5x5. And
you can try the latest 20x20 by increasing the number of matrix. (You can do
the matrix generation with the np.random.random((a,b)) function. It generates
an array of desired sizes between 0-1.)


In [8]:
# YOUR CODE HERE
import numpy as np
np.random.seed(42)
import time

size = 10

# record how long the while loop takes
start = time.time()

while True:
    # generate two random matrices of size 3x3
    a = np.random.random((size, size))
    b = np.random.random((size, size))

    diff = np.abs(a - b)
    # get diagonal of diff
    if np.all(np.diag(diff) <= 0.1):
        print("Found a match!")
        print("matrix 1:")
        print(a)
        print("matrix 2:")
        print(b)
        print("diagonal of diff:")
        print(np.diagonal(diff))
        break

# stop time
end = time.time()
print("Time taken: ", end - start)


[[0.80203982 0.30776679 0.96514057 0.22254882 0.96082357 0.88386248
  0.70451455 0.81831221 0.14548417 0.8959089 ]
 [0.98036683 0.14353201 0.28529909 0.69382485 0.60194746 0.475862
  0.31297111 0.97058358 0.17919567 0.15907398]
 [0.41137242 0.48203334 0.46616916 0.76720021 0.29136543 0.0795811
  0.78117109 0.12738464 0.68651872 0.39496577]
 [0.54496983 0.37466624 0.0617913  0.53042882 0.40448796 0.76969605
  0.20853571 0.51940513 0.91002657 0.00812047]
 [0.51407471 0.65924698 0.27077373 0.26043534 0.87028382 0.48404125
  0.11449501 0.35794764 0.08981719 0.08823397]
 [0.38782498 0.68402206 0.11227034 0.50878429 0.48766131 0.12199372
  0.95849971 0.98251215 0.55170378 0.59825786]
 [0.41522148 0.70202938 0.21248676 0.22896877 0.15433878 0.25010281
  0.46566852 0.06914628 0.39681494 0.55999141]
 [0.41197287 0.69454831 0.32287117 0.96678505 0.83378521 0.7331555
  0.70858667 0.12600876 0.34546425 0.00619238]
 [0.52984152 0.37588775 0.56028108 0.05727417 0.24793042 0.68294765
  0.52578849 0.6